import {useEffect,useState} from 'react';
import {Link,Navigate} from 'react-router-dom';
import {apiRequest,type ProgramAssignment} from '../../lib/api';
import {useAuth} from '../auth/auth-context';

type HomeData={assignment:ProgramAssignment|null;nutrition:Record<string,unknown>|null;checkin:{id:string;dueDate:string;status:string|null}|null;feedbackCount:number;subscription:Record<string,unknown>|null};
export function ClientDashboard(){const{user,ready}=useAuth();const[data,setData]=useState<HomeData|null>(null);const[error,setError]=useState('');useEffect(()=>{if(user?.role==='CLIENT'&&user.approvalStatus==='APPROVED')void Promise.all([apiRequest<{assignment:ProgramAssignment|null}>('/client/program'),apiRequest<{plan:Record<string,unknown>|null}>('/client/nutrition'),apiRequest<{checkins:Array<{id:string;dueDate:string;status:string|null}>}>('/client/checkins'),apiRequest<{messages:unknown[]}>('/feedback?context=GENERAL'),apiRequest<{subscription:Record<string,unknown>|null}>('/client/subscription')]).then(([program,nutrition,checkins,feedback,subscription])=>setData({assignment:program.assignment,nutrition:nutrition.plan,checkin:checkins.checkins.find(item=>item.status!=='REVIEWED')??null,feedbackCount:feedback.messages.length,subscription:subscription.subscription})).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load your home page'));},[user]);if(!ready)return <DashboardSkeleton/>;if(!user)return <Navigate to="/login" replace/>;if(user.role!=='CLIENT')return <Navigate to="/" replace/>;if(user.approvalStatus!=='APPROVED')return <section className="status-page card"><div className="status-icon">⌛</div><p className="eyebrow">Account review</p><h1>Your coach is reviewing your account</h1><p className="lede">You can start onboarding as soon as your coach approves access.</p></section>;
return <section><div className="dashboard-head"><div><p className="eyebrow">Today</p><h1>Hello, {user.displayName}</h1><p className="lede">Here is the simplest next step for your coaching plan.</p></div></div>{error&&<p className="error">{error}</p>}<div className="today-card card"><div><p className="eyebrow">Your next action</p><h2>{data?.assignment?'Continue your training plan':'Complete your onboarding'}</h2><p>{data?.assignment?'Your current program is ready whenever you are.':'Tell your coach about your goals, experience and preferences.'}</p></div><Link className="primary link-button" to={data?.assignment?'/client/hub?tab=program':'/client/hub?tab=onboarding'}>{data?.assignment?'View My Plan':'Start Onboarding'}</Link></div><div className="quick-actions"><Action title="Workout" detail={data?.assignment?.snapshot.name??'No plan assigned'} label="Start Workout" to="/client/hub?tab=program"/><Action title="Nutrition" detail={data?.nutrition?`${String(data.nutrition.daily_calories)} daily calories`:'Targets not assigned'} label="Log Nutrition" to="/client/hub?tab=nutrition"/><Action title="Progress" detail="Record your latest measurements" label="Add Progress" to="/client/hub?tab=progress"/><Action title="Check-in" detail={data?.checkin?`Due ${new Date(data.checkin.dueDate).toLocaleDateString()}`:'Nothing due'} label="Complete Check-in" to="/client/hub?tab=checkins"/><Action title="Coach feedback" detail={`${data?.feedbackCount??0} messages available`} label="Read Feedback" to="/client/hub?tab=feedback"/></div><div className="subscription-strip card"><div><span>Subscription</span><strong>{String(data?.subscription?.plan_name??'No plan')}</strong></div><span className={`status ${String(data?.subscription?.status??'pending').toLowerCase()}`}>{String(data?.subscription?.status??'Not added')}</span></div></section>}
function Action({title,detail,label,to}:{title:string;detail:string;label:string;to:string}){return <article className="card action-card"><span>{title}</span><strong>{detail}</strong><Link to={to}>{label} →</Link></article>}function DashboardSkeleton(){return <section aria-label="Loading dashboard"><div className="skeleton wide"/><div className="quick-actions">{Array.from({length:5},(_,index)=><div className="skeleton card" key={index}/>)}</div></section>}
