import { Collection } from '../../components/collection';
import { EditorDialog } from '../../components/editor-dialog';
import { CheckinPhotos } from './checkin-photos';
import { useEffect, useState, type FormEvent } from 'react';
import { apiRequest, type ClientRelationship } from '../../lib/api';
import { CheckinFields } from './checkin-fields';
import { defaultDefinition, type Checkin, type Definition, type Field } from './checkin-types';
type Form = {id:string;version:number;definition:Definition;isDefault:boolean};
export function CoachCheckins({clients,checkins,onSaved}:{clients:ClientRelationship[];checkins:Checkin[];onSaved:()=>Promise<void>}) {
  const [forms,setForms]=useState<Form[]>([]);
  const [editing,setEditing]=useState<Form|null>(null);
  const [editorKey,setEditorKey]=useState(0);const[editorOpen,setEditorOpen]=useState(false);const[assignOpen,setAssignOpen]=useState(false);const[dialogBusy,setDialogBusy]=useState(false);
  const [message,setMessage]=useState('');
  const [filter,setFilter]=useState('');
  const [status,setStatus]=useState('ALL');
  async function loadForms(){try{setForms((await apiRequest<{forms:Form[]}>('/coach/checkins/forms')).forms);}catch(error){setMessage(error instanceof Error?error.message:'Unable to load forms');}}
  useEffect(()=>{void loadForms();},[]);
  const visible=checkins.filter(checkin=>(checkin.status==='SUBMITTED'||checkin.status==='REVIEWED')&&(!filter||checkin.clientId===filter)&&(status==='ALL'||checkin.status===status));
  return <div>
    {message&&<p role="status">{message}</p>}
    {editorOpen&&<EditorDialog title={editing?'Edit check-in form':'Add check-in form'} busy={dialogBusy} onClose={()=>setEditorOpen(false)}><FormBuilder key={editorKey} initial={editing} onBusy={setDialogBusy} onSaved={async()=>{await loadForms();setEditorOpen(false);setMessage('Form published. Existing assignments retain their original questions.');}}/></EditorDialog>}
    {assignOpen&&<EditorDialog title="Assign check-ins" busy={dialogBusy} onClose={()=>setAssignOpen(false)}><AssignCheckins forms={forms} clients={clients} onBusy={setDialogBusy} onSaved={async()=>{await onSaved();setAssignOpen(false);}}/></EditorDialog>}
    <Collection title="Published forms" actions={<><button className="secondary" onClick={()=>setAssignOpen(true)}>Assign check-ins</button><button className="primary" onClick={()=>{setEditing(null);setEditorKey(value=>value+1);setEditorOpen(true);}}>New form</button></>}>{forms.map(form=><div className="list-item" key={form.id}><div><strong>{form.definition.name}</strong><p>Version {form.version} · {form.definition.fields.length} questions {form.isDefault?'· Default':''}</p></div><button className="secondary" onClick={()=>{setEditing(form);setEditorKey(value=>value+1);setEditorOpen(true);}}>Edit</button></div>)}</Collection>
    <h2>Check-in history</h2><div className="actions"><label>Client filter<select value={filter} onChange={event=>setFilter(event.target.value)}><option value="">All clients</option>{clients.map(client=><option key={client.clientId} value={client.clientId}>{client.client.displayName}</option>)}</select></label><label>Status filter<select value={status} onChange={event=>setStatus(event.target.value)}>{['ALL','SUBMITTED','REVIEWED'].map(value=><option key={value}>{value}</option>)}</select></label></div>
    <MetricHistory checkins={visible}/>
    {visible.length===0&&<p>No submitted check-ins match these filters.</p>}
    <Collection title="Check-in submissions">{visible.map(checkin=><div key={`${checkin.id}-${checkin.revision}`} data-search={`${checkin.clientName} ${checkin.dueDate} ${checkin.status} ${checkin.form.name}`}><ReviewCheckin checkin={checkin} onSaved={onSaved}/></div>)}</Collection>
  </div>;
}
function FormBuilder({initial,onSaved,onBusy}:{onBusy:(busy:boolean)=>void;initial:Form|null;onSaved:()=>Promise<void>}) {
  const [definition,setDefinition]=useState<Definition>(initial?.definition??structuredClone(defaultDefinition));
  const [isDefault,setDefault]=useState(initial?.isDefault??false);
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState('');
  function update(id:string,patch:Partial<Field>){setDefinition(current=>({...current,fields:current.fields.map(field=>field.id===id?{...field,...patch}:field)}));}
  function move(index:number,offset:number){setDefinition(current=>{const fields=[...current.fields];const item=fields.splice(index,1)[0]!;fields.splice(index+offset,0,item);return {...current,fields};});}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);onBusy(true);try{await apiRequest(`/coach/checkins/forms${initial?`/${initial.id}`:''}`,{method:initial?'PUT':'POST',body:JSON.stringify({definition,isDefault,...(initial?{version:initial.version}:{})})});await onSaved();}catch(error){setMessage(error instanceof Error?error.message:'Unable to publish form');}finally{setBusy(false);onBusy(false);}}
  return <form className="card profile-card vertical" onSubmit={save}><h2>{initial?'Edit check-in form':'Create check-in form'}</h2>{message&&<p role="alert">{message}</p>}<fieldset className="checkin-fields" disabled={busy}>
    <label>Form name<input minLength={2} maxLength={150} required value={definition.name} onChange={event=>setDefinition(current=>({...current,name:event.target.value}))}/></label><label className="check"><input type="checkbox" checked={isDefault} onChange={event=>setDefault(event.target.checked)}/>Default form</label>
    {definition.fields.map((field,index)=><fieldset className="checkin-fields" key={field.id}><legend>Question {index+1}</legend><label>Question<input required maxLength={200} value={field.label} onChange={event=>update(field.id,{label:event.target.value})}/></label>
      <label>Answer type<select value={field.type} onChange={event=>{const type=event.target.value as Field['type'];setDefinition(current=>({...current,fields:current.fields.map(item=>item.id===field.id?{id:item.id,label:item.label,required:item.required,type,...(type==='RATING'?{min:1,max:10}:{}),metric:false}:item)}));}}>{['NUMBER','RATING','SHORT_TEXT','LONG_TEXT'].map(type=><option key={type} value={type}>{type.replaceAll('_',' ')}</option>)}</select></label>
      <label className="check"><input type="checkbox" checked={field.required} onChange={event=>update(field.id,{required:event.target.checked})}/>Required</label>
      {(field.type==='NUMBER'||field.type==='RATING')&&<><div className="form-row"><label>Minimum<input type="number" step="any" required={field.type==='RATING'} value={field.min??''} onChange={event=>update(field.id,{min:event.target.value===''?undefined:Number(event.target.value)})}/></label><label>Maximum<input type="number" step="any" required={field.type==='RATING'} value={field.max??''} onChange={event=>update(field.id,{max:event.target.value===''?undefined:Number(event.target.value)})}/></label><label>Unit<input maxLength={20} value={field.unit??''} onChange={event=>update(field.id,{unit:event.target.value})}/></label></div>
      <label className="check"><input type="checkbox" checked={field.metric??false} onChange={event=>update(field.id,{metric:event.target.checked})}/>Show in metric history</label><label>Attention rule<select value={field.flag?.operator??''} onChange={event=>update(field.id,{flag:event.target.value?{operator:event.target.value as 'GT'|'LT',value:field.flag?.value??5}:undefined})}><option value="">No rule</option><option value="GT">Above</option><option value="LT">Below</option></select></label>{field.flag&&<label>Threshold<input type="number" step="any" required value={field.flag.value} onChange={event=>update(field.id,{flag:{operator:field.flag!.operator,value:Number(event.target.value)}})}/></label>}</>}
      <div className="actions"><button type="button" className="secondary" disabled={index===0} onClick={()=>move(index,-1)}>Move up</button><button type="button" className="secondary" disabled={index===definition.fields.length-1} onClick={()=>move(index,1)}>Move down</button><button type="button" className="danger" disabled={definition.fields.length===1} onClick={()=>setDefinition(current=>({...current,fields:current.fields.filter(item=>item.id!==field.id)}))}>Remove question</button></div>
    </fieldset>)}
    <button type="button" className="secondary" disabled={definition.fields.length>=50} onClick={()=>setDefinition(current=>({...current,fields:[...current.fields,{id:`q${crypto.randomUUID().replaceAll('-','')}`,label:'New question',type:'SHORT_TEXT',required:false}]}))}>Add question</button>
    <details><summary>Preview client form</summary><div className="checkin-fields"><CheckinFields definition={definition} answers={{}} disabled onChange={()=>{}}/></div></details>
    <button className="primary">{busy?'Publishing…':'Save and publish'}</button></fieldset></form>;
}
function AssignCheckins({forms,clients,onSaved,onBusy}:{onBusy:(busy:boolean)=>void;forms:Form[];clients:ClientRelationship[];onSaved:()=>Promise<void>}) {
  const [busy,setBusy]=useState(false);const[message,setMessage]=useState('');const [frequency,setFrequency]=useState('DAILY');
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget;const data=new FormData(form);setBusy(true);onBusy(true);try{const result=await apiRequest<{assignmentIds:string[]}>('/coach/checkins',{method:'POST',body:JSON.stringify({formId:String(data.get('formId')),clientIds:data.getAll('clients'),dueDate:String(data.get('date')),frequency,occurrences:frequency==='ONCE'?1:Number(data.get('occurrences')),notes:String(data.get('notes'))})});setMessage(`${result.assignmentIds.length} check-ins assigned.`);await onSaved();}catch(error){setMessage(error instanceof Error?error.message:'Unable to assign');}finally{setBusy(false);onBusy(false);}}
  return <form className="card profile-card vertical" onSubmit={save}><h2>Assign check-ins</h2>{message&&<p role="status">{message}</p>}<fieldset disabled={busy} className="checkin-fields"><label>Form<select name="formId" required defaultValue=""><option value="">Choose form</option>{forms.map(form=><option key={form.id} value={form.id}>{form.definition.name}{form.isDefault?' (Default)':''}</option>)}</select></label><fieldset><legend>Clients</legend>{clients.map(client=><label className="check" key={client.clientId}><input type="checkbox" name="clients" value={client.clientId}/>{client.client.displayName}</label>)}</fieldset><label>First due date<input name="date" type="date" required/></label><label>Frequency<select value={frequency} onChange={event=>setFrequency(event.target.value)}><option value="ONCE">Once</option><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="BIWEEKLY">Every two weeks</option><option value="MONTHLY">Monthly</option></select></label>{frequency!=='ONCE'&&<label>Number of check-ins<input name="occurrences" type="number" min={1} max={366} defaultValue={30} required/></label>}<label>Instructions<textarea name="notes" maxLength={2000}/></label><p>One check-in is created on each scheduled date. The same form can only be assigned once per client per date; different forms can share a date. Each submission requires answers to the required questions and at least one photo.</p><button className="primary" disabled={!forms.length||!clients.length}>{busy?'Assigning…':'Assign check-ins'}</button></fieldset></form>;
}
function ReviewCheckin({checkin,onSaved}:{checkin:Checkin;onSaved:()=>Promise<void>}) {
  const [busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[history,setHistory]=useState<Array<{id:string;action:string;revision:number;createdAt:string;snapshot:Record<string,unknown>}>>([]);
  async function review(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const data=new FormData(event.currentTarget);setBusy(true);try{await apiRequest(`/coach/checkins/${checkin.id}/review`,{method:'POST',body:JSON.stringify({revision:checkin.revision,status:String(data.get('status')),notes:String(data.get('notes'))})});await onSaved();}catch(error){setMessage(error instanceof Error?error.message:'Unable to review');}finally{setBusy(false);}}
  async function showHistory(){try{setHistory((await apiRequest<{history:typeof history}>(`/coach/checkins/${checkin.id}/history`)).history);}catch(error){setMessage(error instanceof Error?error.message:'Unable to load history');}}
  async function reschedule(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const dueDate=String(new FormData(event.currentTarget).get('dueDate'));setBusy(true);try{await apiRequest(`/coach/checkins/${checkin.id}/reschedule`,{method:'POST',body:JSON.stringify({dueDate,previousDate:checkin.dueDate})});await onSaved();}catch(error){setMessage(error instanceof Error?error.message:'Unable to reschedule');}finally{setBusy(false);}}
  return <details className="card plan-summary"><summary><strong>{checkin.clientName}</strong> · {checkin.dueDate} · {checkin.form.name} · {checkin.status.toLowerCase()}{checkin.reviewStatus?` · ${checkin.reviewStatus.replaceAll('_',' ')}`:''}</summary>
    {message&&<p role="alert">{message}</p>}{checkin.flags?.map(flag=><p className="checkin-flag" key={flag.id}>Needs attention: {flag.label} ({flag.value})</p>)}
    {['PENDING','DRAFT'].includes(checkin.status)&&<form className="checkin-fields" onSubmit={reschedule}><label>Due date<input type="date" name="dueDate" defaultValue={checkin.dueDate} required/></label><button className="secondary" disabled={busy}>Change due date</button></form>}
    <details><summary>View check-in photos</summary><CheckinPhotos id={checkin.id} coach locked/></details>
    <dl>{checkin.form.fields.map(field=><div className="summary-row" key={field.id}><dt>{field.label}</dt><dd>{checkin.data?.[field.id]??'—'} {field.unit}</dd></div>)}</dl>
    {['SUBMITTED','REVIEWED'].includes(checkin.status)&&<form className="checkin-fields" onSubmit={review}><label>Review status<select name="status" defaultValue={checkin.reviewStatus??'NEUTRAL'}><option value="ON_TRACK">On Track</option><option value="NEUTRAL">Neutral</option><option value="NEEDS_ATTENTION">Needs Attention</option></select></label><label>Feedback to client<textarea name="notes" maxLength={4000} defaultValue={checkin.reviewNotes??''}/></label><button className="primary" disabled={busy}>Save review</button></form>}
    <button className="secondary" onClick={()=>void showHistory()}>View audit history</button>{history.map(entry=><details key={entry.id}><summary>{new Date(entry.createdAt).toLocaleString()} · {entry.action.replaceAll('_',' ')} · Revision {entry.revision}</summary><p>{String(entry.snapshot.status??'')} {String(entry.snapshot.notes??'')}{entry.snapshot.dueDate?`Due ${String(entry.snapshot.dueDate)}`:''}</p>{entry.snapshot.answers&&typeof entry.snapshot.answers==='object'?<dl>{Object.entries(entry.snapshot.answers).map(([id,value])=><div className="summary-row" key={id}><dt>{checkin.form.fields.find(field=>field.id===id)?.label??id}</dt><dd>{String(value)}</dd></div>)}</dl>:null}</details>)}
  </details>;
}
function MetricHistory({checkins}:{checkins:Checkin[]}) {
  const [hidden,setHidden]=useState<string[]>([]);
  const [metric,setMetric]=useState('');
  const fields=[...new Map(checkins.flatMap(checkin=>checkin.form.fields.filter(field=>field.metric).map(field=>{const key=`${checkin.formId??'legacy'}:${field.id}:${field.unit??''}`;return [key,{...field,key,formId:checkin.formId,formName:checkin.form.name}] as const;}))).values()];
  const shown=fields.filter(field=>!hidden.includes(field.key));
  const entries=checkins.filter(checkin=>['SUBMITTED','REVIEWED'].includes(checkin.status));
  const selected=fields.find(field=>field.key===metric);
  const points=selected?entries.filter(checkin=>checkin.formId===selected.formId&&typeof checkin.data[selected.id]==='number').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).map(checkin=>({date:checkin.dueDate,value:Number(checkin.data[selected.id])})):[];
  const low=Math.min(...points.map(point=>point.value)),high=Math.max(...points.map(point=>point.value));
  return <><details><summary>Customize metric columns</summary>{fields.map(field=><label className="check" key={field.key}><input type="checkbox" checked={!hidden.includes(field.key)} onChange={event=>setHidden(current=>event.target.checked?current.filter(id=>id!==field.key):[...current,field.key])}/>{field.formName} · {field.label}</label>)}</details>
    {new Set(entries.map(checkin=>checkin.clientId)).size===1&&<div><label>Trend metric<select value={metric} onChange={event=>setMetric(event.target.value)}><option value="">Choose a metric</option>{fields.map(field=><option key={field.key} value={field.key}>{field.formName} · {field.label} {field.unit}</option>)}</select></label>{points.length>1&&<figure><svg role="img" aria-label={`${selected?.label} over check-in dates`} viewBox="0 0 600 180"><polyline fill="none" stroke="#087957" strokeWidth="3" points={points.map((point,index)=>`${20+index*560/(points.length-1)},${150-(point.value-low)*120/(high-low||1)}`).join(' ')}/>{points.map((point,index)=><circle key={index} cx={20+index*560/(points.length-1)} cy={150-(point.value-low)*120/(high-low||1)} r="4" fill="#087957"><title>{point.date}: {point.value} {selected?.unit}</title></circle>)}</svg><figcaption>{points[0]?.date} to {points.at(-1)?.date} · Range {low}–{high} {selected?.unit}</figcaption></figure>}</div>}
    {entries.length>0&&<div className="checkin-metrics"><table><caption>Submitted numeric history</caption><thead><tr><th>Client</th><th>Due date</th>{shown.map(field=><th key={field.key}>{field.label} {field.unit}</th>)}</tr></thead><tbody>{entries.map(checkin=><tr key={checkin.id}><td>{checkin.clientName}</td><td>{checkin.dueDate}</td>{shown.map(field=><td key={field.key}>{checkin.formId===field.formId?checkin.data[field.id]??'—':'—'}</td>)}</tr>)}</tbody></table></div>}</>;
}
