import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { apiRequest, type User } from '../../lib/api';

export function CoachRegisterPage() {
  const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); try { await apiRequest<{ user: User }>('/auth/coach/register', { method: 'POST', body: JSON.stringify(Object.fromEntries(data)) }); navigate('/login', { state: { registered: true } }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to register'); } finally { setBusy(false); } }
  return <div className="auth-grid"><section><p className="eyebrow">Coach application</p><h1>Build a better coaching experience.</h1><p className="lede">Create your account. A platform administrator reviews every coach before access is enabled.</p><div className="steps"><span>1</span><p><strong>Apply</strong><br />Tell us about you and your business.</p><span>2</span><p><strong>Review</strong><br />The platform admin approves your account.</p><span>3</span><p><strong>Coach</strong><br />Enter your secure workspace.</p></div></section><form className="card form-card" onSubmit={submit}><h2>Create coach account</h2><label>Your name<input name="displayName" minLength={2} required /></label><label>Business name<input name="businessName" minLength={2} required /></label><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" minLength={12} required /><small>At least 12 characters</small></label>{error && <p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Submitting…' : 'Submit application'}</button><p className="helper">Already registered? <Link to="/login">Sign in</Link></p></form></div>;
}
