import { LoadingPanel } from '../../components/loading-panel';
import { Collection } from '../../components/collection';
import { EditorDialog, Notice } from '../../components/editor-dialog';
import { CoachCheckins } from '../checkins/coach-checkins';
import type { Checkin } from '../checkins/checkin-types';
import { NutritionStudio } from './nutrition-studio';
import { useCallback,useEffect,useState,type FormEvent,type ReactNode } from 'react';
import { Navigate,useSearchParams } from 'react-router-dom';
import { apiRequest,type ClientRelationship,type Exercise,type Program,type WorkoutTemplate } from '../../lib/api';
import { useAuth } from '../auth/auth-context';
import { ExerciseLibrary } from './exercise-library';
import { WorkoutTemplateForm } from './workout-template-form';
import { ProgramForm } from './program-form';

type Session={id:string;clientName:string;status:string;workoutSnapshot:{name?:string};startedAt:string};
export function CoachMvpPage(){const{user,ready}=useAuth();const[searchParams]=useSearchParams();const[clients,setClients]=useState<ClientRelationship[]>([]);const[templates,setTemplates]=useState<WorkoutTemplate[]>([]);const[programs,setPrograms]=useState<Program[]>([]);const[checkins,setCheckins]=useState<Checkin[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[exercises,setExercises]=useState<Exercise[]>([]);const[clientId,setClientId]=useState('');const tab=searchParams.get('tab')??'workouts';const[message,setMessage]=useState('');const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState('');const[busy,setBusy]=useState(false);const[workoutEditor,setWorkoutEditor]=useState<WorkoutTemplate|null|undefined>();const[programEditor,setProgramEditor]=useState<Program|null|undefined>();
const load=useCallback(async()=>{setLoading(true);setLoadError('');try{const[c,t,p,ch,w,e]=await Promise.all([apiRequest<{relationships:ClientRelationship[]}>('/coach/clients'),apiRequest<{templates:WorkoutTemplate[]}>('/coach/workout-templates'),apiRequest<{programs:Program[]}>('/coach/programs'),apiRequest<{checkins:Checkin[]}>('/coach/checkins'),apiRequest<{sessions:Session[]}>('/coach/workouts'),apiRequest<{items:Exercise[]}>('/exercises?limit=50')]);setClients(c.relationships.filter(r=>r.status==='APPROVED'));setTemplates(t.templates);setPrograms(p.programs);setCheckins(ch.checkins);setSessions(w.sessions);setExercises(e.items);setClientId(current=>current||c.relationships.find(r=>r.status==='APPROVED')?.clientId||'');}catch(error){setLoadError(error instanceof Error?error.message:'Unable to load workbench');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);if(!ready)return <p>Loading…</p>;if(!user)return <Navigate to="/login"/>;if(user.role!=='COACH')return <Navigate to="/"/>;
async function submit(path:string,event:FormEvent<HTMLFormElement>,build:(data:FormData)=>unknown){event.preventDefault();if(busy)return;const form=event.currentTarget;setBusy(true);try{await apiRequest(path,{method:'POST',body:JSON.stringify(build(new FormData(form)))});setMessage('Saved successfully.');form.reset();await load();}catch(error){setLoadError(error instanceof Error?error.message:'Action failed');}finally{setBusy(false);}}
async function action(path:string,body:unknown={}){if(busy)return;setBusy(true);try{await apiRequest(path,{method:'POST',body:JSON.stringify(body)});setMessage('Action completed.');await load();}catch(error){setLoadError(error instanceof Error?error.message:'Action failed');}finally{setBusy(false);}}
const approvedClients=clients;return <section><div className="dashboard-head"><div><p className="eyebrow">Coach workspace</p><h1>{tab==='nutrition'?('Nutrition '+({days:'Days',meals:'Meals',foods:'Foods'}[searchParams.get('section') as 'days'|'meals'|'foods']??'Plans')):tab==='exercises'?'Exercise library':tab==='workouts'?'Workout builder':tab==='programs'?'Programs':tab==='clients'?'Client services':tab==='checkins'?'Check-ins':'Client activity'}</h1><p className="lede">Build plans, review client activity, and manage the coaching workflow.</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></div><Notice message={message} onClear={()=>setMessage('')}/><Notice message={loadError} error onClear={()=>setLoadError('')}/>{loading&&<LoadingPanel label="Loading workspace…"/>}
{tab==='nutrition'&&<NutritionStudio clients={approvedClients}/>}
{tab==='exercises'&&<ExerciseLibrary/>}
{tab==='workouts'&&<>{workoutEditor!==undefined&&<EditorDialog title={workoutEditor?'Edit workout':'Add workout'} busy={busy} onClose={()=>setWorkoutEditor(undefined)}><WorkoutTemplateForm initial={workoutEditor??undefined} exercises={exercises} onBusy={setBusy} onSaved={async()=>{setWorkoutEditor(undefined);await load();}} onMessage={setMessage}/></EditorDialog>}<Collection title="Workout templates" loading={loading} error={loadError} onRetry={()=>void load()} actions={<button className="primary" onClick={()=>setWorkoutEditor(null)}>Add workout</button>}>{templates.filter(t=>!t.archived_at).map(t=><article className="list-item" key={t.id}><div><strong>{t.name}</strong><p>{t.exercises.length} exercises · {t.description||'No description'}</p></div><div className="actions"><button className="secondary" onClick={()=>setWorkoutEditor(t)}>Edit</button><button className="danger" disabled={busy} onClick={async()=>{if(!confirm('Archive this workout? Existing assigned workouts are preserved.'))return;setBusy(true);try{await apiRequest(`/coach/workout-templates/${t.id}`,{method:'DELETE'});setMessage('Workout archived.');await load();}catch(error){setLoadError(error instanceof Error?error.message:'Unable to archive workout');}finally{setBusy(false);}}}>Archive</button></div></article>)}</Collection></>}
{tab==='programs'&&<>{programEditor!==undefined&&<EditorDialog title={programEditor?'Edit program':'Add program'} busy={busy} onClose={()=>setProgramEditor(undefined)}><ProgramForm initial={programEditor??undefined} templates={templates} onBusy={setBusy} onSaved={async()=>{setProgramEditor(undefined);await load();}} onMessage={setMessage}/></EditorDialog>}<Collection title="Programs" loading={loading} error={loadError} onRetry={()=>void load()} actions={<button className="primary" onClick={()=>setProgramEditor(null)}>Add program</button>}>{programs.filter(p=>p.status!=='ARCHIVED').map(p=><article className="list-item" key={p.id}><div><strong>{p.name}</strong><p>{p.days.length} workout days</p><span className={`status ${p.status.toLowerCase()}`}>{p.status}</span></div><div className="actions"><button className="danger" disabled={busy} onClick={async()=>{if(!confirm('Archive this program? Existing client assignments are preserved.'))return;setBusy(true);try{await apiRequest(`/coach/programs/${p.id}`,{method:'DELETE'});setMessage('Program archived.');await load();}catch(error){setLoadError(error instanceof Error?error.message:'Unable to archive program');}finally{setBusy(false);}}}>Archive</button>{p.status==='DRAFT' &&<><button className="secondary" onClick={()=>setProgramEditor(p)}>Edit</button><button className="secondary" disabled={busy} onClick={()=>void action(`/coach/programs/${p.id}/publish`)}>Publish</button></>}{p.status==='PUBLISHED'&&<><select aria-label={`Client for ${p.name}`} value={clientId} onChange={e=>setClientId(e.target.value)}>{approvedClients.map(c=><option value={c.clientId} key={c.clientId}>{c.client.displayName}</option>)}</select><button className="primary small" disabled={busy||!clientId} onClick={()=>void action(`/coach/programs/${p.id}/assign`,{clientId})}>Assign</button></>}</div></article>)}</Collection></>}
{tab==='clients'&&<div className="workbench-grid"><div className="card plan-summary"><h2>Nutrition plans</h2><p>Create foods, meals and days, then assign a complete plan to your client.</p><a className="primary" href="/coach/studio?tab=nutrition">Open nutrition builder</a></div><form className="card profile-card vertical" onSubmit={e=>void submit('/coach/subscription',e,d=>({clientId:String(d.get('clientId')),planName:String(d.get('planName')),status:String(d.get('status')),startsOn:String(d.get('startsOn')),endsOrRenewsOn:String(d.get('end'))||null,amount:Number(d.get('amount'))||null,currency:String(d.get('currency'))||null,notes:String(d.get('notes'))}))}><h2>Subscription status</h2><ClientSelect clients={approvedClients}/><label>Plan name<input name="planName" required/></label><label>Status<select name="status">{['ACTIVE','PENDING','PAUSED','CANCELLED','EXPIRED'].map(s=><option key={s}>{s}</option>)}</select></label><div className="form-row"><label>Starts<input type="date" name="startsOn" required/></label><label>Renews / ends<input type="date" name="end"/></label></div><div className="form-row"><label>Amount<input type="number" min="0" step=".01" name="amount"/></label><label>Currency<input name="currency" maxLength={3} placeholder="USD"/></label></div><label>Notes<textarea name="notes"/></label><button className="primary" disabled={busy}>Save subscription</button></form><form className="card profile-card vertical" onSubmit={e=>void submit('/feedback',e,d=>({clientId:String(d.get('clientId')),context:'GENERAL',contextId:null,message:String(d.get('message'))}))}><h2>Send feedback</h2><ClientSelect clients={approvedClients}/><label>Message<textarea name="message" required/></label><button className="primary" disabled={busy}>Post message</button></form></div>}
{tab==='checkins'&&<CoachCheckins clients={approvedClients} checkins={checkins} onSaved={load}/>}
{tab==='activity'&&<List title="Client workout activity">{sessions.map(s=><article className="list-item" key={s.id}><div><strong>{s.clientName} · {s.workoutSnapshot.name??'Workout'}</strong><p>{new Date(s.startedAt).toLocaleString()}</p></div><span className={`status ${s.status.toLowerCase()}`}>{s.status}</span></article>)}</List>}</section>;}
function ClientSelect({clients}:{clients:ClientRelationship[]}){return <label>Client<select name="clientId" required>{clients.map(c=><option key={c.clientId} value={c.clientId}>{c.client.displayName}</option>)}</select></label>}function List({title,children}:{title:string;children:ReactNode}){return <Collection title={title}>{children}</Collection>}
