import { ClientWizard } from './client-wizard';
import { Collection } from '../../components/collection';
import { EditorDialog, Notice } from '../../components/editor-dialog';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link, Navigate, useSearchParams } from 'react-router-dom';
import { apiRequest, type ClientRelationship, type Invitation } from '../../lib/api';
import { useAuth } from '../auth/auth-context';

export function CoachDashboard() {
  const { user, ready, updateProfile } = useAuth(); const [relationships, setRelationships] = useState<ClientRelationship[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]); const [inviteLink, setInviteLink] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState('');
  const [wizard,setWizard]=useState<string|null|undefined>(undefined);const [inviteOpen,setInviteOpen]=useState(false);const[loading,setLoading]=useState(true);
 const [searchParams]=useSearchParams();
  const requestedTab=searchParams.get('tab');const tab=requestedTab==='invitations'||requestedTab==='profile'?requestedTab:'clients';
  const load = useCallback(async () => { if (user?.role === 'COACH' && user.approvalStatus === 'APPROVED') { setLoading(true);try { const [clientResult, invitationResult] = await Promise.all([apiRequest<{ relationships: ClientRelationship[] }>('/coach/clients'), apiRequest<{ invitations: Invitation[] }>('/coach/invitations')]); setRelationships(clientResult.relationships); setInvitations(invitationResult.invitations); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load coach workspace'); }finally{setLoading(false);} } }, [user]);
  useEffect(() => { void load(); }, [load]);
  if (!ready) return <p>Loading session…</p>; if (!user) return <Navigate to="/login" replace />; if (user.role !== 'COACH') return <Navigate to="/" replace />; if (user.approvalStatus !== 'APPROVED') return <PendingCoach status={user.approvalStatus} />;
  async function createInvite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=event.currentTarget; const email=String(new FormData(form).get('email')??''); setBusy('invite'); setError(''); try { const result=await apiRequest<{invitation:{token:string}}>('/coach/invitations',{method:'POST',body:JSON.stringify({email})}); setInviteLink(`${window.location.origin}/register/client?invite=${encodeURIComponent(result.invitation.token)}`); form.reset(); await load(); } catch(caught){setError(caught instanceof Error?caught.message:'Unable to create invitation');} finally{setBusy('');} }
  async function decide(relationship:ClientRelationship,action:'approve'|'reject'){const reason=action==='reject'?window.prompt('Why are you rejecting this client?'):null;if(action==='reject'&&!reason)return;setBusy(relationship.id);try{await apiRequest(`/coach/clients/${relationship.id}/${action}`,{method:'POST',body:JSON.stringify(reason?{reason}:{})});await load();}catch(caught){setError(caught instanceof Error?caught.message:'Unable to update client');}finally{setBusy('');}}
  async function revoke(invitation:Invitation){setBusy(invitation.id);try{await apiRequest(`/coach/invitations/${invitation.id}`,{method:'DELETE'});await load();}catch(caught){setError(caught instanceof Error?caught.message:'Unable to revoke invitation');}finally{setBusy('');}}
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy('profile');try{await updateProfile(String(data.get('displayName')),String(data.get('businessName')));setNotice('Profile saved successfully.');}catch(caught){setError(caught instanceof Error?caught.message:'Unable to save profile');}finally{setBusy('');}}
  const pending=relationships.filter((relationship)=>relationship.status==='PENDING_REVIEW').length;const active=relationships.filter((relationship)=>relationship.status==='APPROVED').length;const openInvites=invitations.filter((invitation)=>invitation.status==='PENDING').length;
  if(wizard!==undefined)return <ClientWizard {...(wizard?wizard.startsWith('invite:')?{invitationId:wizard.slice(7)}:{clientId:wizard}:{})} onClose={()=>setWizard(undefined)} onSaved={load}/>;
  return <section><div className="dashboard-head"><div><p className="eyebrow">Coach dashboard</p><h1>What needs your attention</h1><p className="lede">Approve clients first, then create and assign their coaching plan.</p><div className="hero-actions"><button className="primary" onClick={()=>setWizard(null)}>Add client</button><Link className="secondary link-button" to="/coach/studio?tab=programs">Create Program</Link></div></div><button className="secondary" onClick={()=>void load()}>Refresh</button></div><Notice message={error} error onClear={()=>setError('')}/><Notice message={notice} onClear={()=>setNotice('')}/>
    <div className="dashboard-grid"><Metric label="Active clients" value={active}/><Metric label="Pending clients" value={pending}/><Metric label="Open invitations" value={openInvites}/></div>
    {tab==='clients'&&<Collection title="Client access" loading={loading} error={error} onRetry={()=>void load()} actions={<button className="primary" onClick={()=>setWizard(null)}>Add client</button>}>{relationships.map((relationship)=><article className="client-row" key={relationship.id}><div className="avatar">{relationship.client.displayName[0]}</div><div className="coach-main"><strong>{relationship.client.displayName}</strong><span>{relationship.client.email}</span></div><span className={`status ${relationship.status.toLowerCase()}`}>{relationship.status.replace('_',' ')}</span>{['APPROVED','PENDING_REVIEW'].includes(relationship.status)&&<button className="secondary" onClick={()=>setWizard(relationship.clientId)}>Edit client</button>}{relationship.status==='PENDING_REVIEW'&&<div className="actions"><button className="danger" disabled={busy===relationship.id} onClick={()=>void decide(relationship,'reject')}>Reject</button><button className="primary small" disabled={busy===relationship.id} onClick={()=>void decide(relationship,'approve')}>Approve</button></div>}</article>)}</Collection>}
    {tab==='invitations'&&<>{inviteOpen&&<EditorDialog title="Invite a client" busy={busy==='invite'} onClose={()=>setInviteOpen(false)}><Notice message={error} error onClear={()=>setError('')}/><form className="card invite-card" onSubmit={createInvite}><h2>Invite a client</h2><p>Generate a private, single-use registration link valid for seven days.</p><label>Client email<input name="email" type="email" required placeholder="client@example.com"/></label><button className="primary" disabled={busy==='invite'}>{busy==='invite'?'Creating…':'Create invitation'}</button>{inviteLink&&<div className="invite-result"><strong>Invitation ready</strong><input aria-label="Invitation link" readOnly value={inviteLink}/><button type="button" className="secondary" onClick={()=>void navigator.clipboard.writeText(inviteLink).then(()=>setNotice('Link copied.')).catch(()=>setError('Unable to copy. Select and copy the invitation link manually.'))}>Copy link</button></div>}</form></EditorDialog>}<Collection title="Invitation history" loading={loading} error={error} onRetry={()=>void load()} actions={<button className="primary" onClick={()=>{setInviteLink('');setInviteOpen(true);}}>Add invitation</button>}>{invitations.map((invitation)=><article className="audit-row" key={invitation.id}><span className="audit-icon">✉</span><div><strong>{invitation.email}</strong><p>Created {new Date(invitation.createdAt).toLocaleString()}</p></div><span className={`status ${invitation.status.toLowerCase()}`}>{invitation.status}</span>{invitation.status==='PENDING'&&<button className="secondary" onClick={()=>setWizard('invite:'+invitation.id)}>Edit setup</button>}{invitation.status==='PENDING'&&<button className="danger" disabled={busy===invitation.id} onClick={()=>void revoke(invitation)}>Revoke</button>}</article>)}</Collection></>}
    {tab==='profile'&&<form className="card profile-card" onSubmit={saveProfile}><div><p className="eyebrow">Public identity</p><h2>Business profile</h2><p>Keep the identity shown to clients up to date.</p></div><label>Display name<input name="displayName" defaultValue={user.displayName} required minLength={2}/></label><label>Business name<input name="businessName" defaultValue={user.businessName??''} required minLength={2}/></label><label>Email<input value={user.email} readOnly/><small>Email changes require platform support.</small></label><button className="primary" disabled={busy==='profile'}>{busy==='profile'?'Saving…':'Save profile'}</button></form>}
  </section>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="card metric-card"><span>{label}</span><strong>{value}</strong></div>;}
function PendingCoach({status}:{status:string}){return <section className="status-page card"><div className="status-icon">⌛</div><p className="eyebrow">Application status</p><h1>{status==='PENDING_REVIEW'?'Your application is under review':`Application ${status.toLowerCase()}`}</h1><p className="lede">{status==='PENDING_REVIEW'?'A platform administrator will review your coach account. Sign in anytime to check its status.':'Contact the platform administrator if you need more information.'}</p><div className="status-line"><span>Account created</span><strong>Complete</strong></div><div className="status-line"><span>Admin review</span><strong>{status.replace('_',' ')}</strong></div><div className="status-line muted"><span>Coach workspace</span><strong>Locked</strong></div></section>;}
