import '@testing-library/jest-dom/vitest';
import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { apiRequest, type Exercise } from '../../lib/api';
import { ExerciseLibrary } from './exercise-library';
vi.mock('../../lib/api', () => ({ apiRequest: vi.fn() }));
vi.mock('../../components/exercise-gif', () => ({ ExerciseGif: () => <span>Animation</span> }));
vi.mock('./exercise-form',()=>({ExerciseForm:({onSaved}:{onSaved:(exercise:Exercise)=>void})=><button onClick={()=>onSaved({...exercise,name:'Leg raises'})}>Save exercise</button>}));
afterEach(() => { cleanup(); vi.useRealTimers(); vi.resetAllMocks(); });
const exercise: Exercise = { id: '001', name: 'Squat', target: 'quads', bodyPart: 'legs', equipment: 'body weight', instructions: ['Bend your knees.'], secondaryMuscles: [], gifAvailable: true };
it('clears the creation search and keeps the table visible while refetching the library',async()=>{
  HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
  HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
  vi.mocked(apiRequest).mockResolvedValue({items:[exercise],total:25});
  await act(async()=>{render(<ExerciseLibrary/>);});
  fireEvent.change(screen.getByRole('searchbox'),{target:{value:'Squat'}});
  fireEvent.submit(screen.getByRole('searchbox').closest('form')!);
  await act(async()=>{});
  let finish!: (value:unknown)=>void;
  vi.mocked(apiRequest).mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));
  fireEvent.click(screen.getByRole('button',{name:'Add exercise'}));
  await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Save exercise'}));});
  expect(screen.getByRole('searchbox')).toHaveValue('');
  expect(apiRequest).toHaveBeenLastCalledWith('/exercises?q=&page=1&limit=10');
  expect(screen.getByRole('table')).toBeInTheDocument();
  expect(screen.getByRole('rowheader',{name:'Squat'})).toBeInTheDocument();
  await act(async()=>{finish({items:[exercise,{...exercise,id:'new',name:'Leg raises'}],total:26});});
  expect(screen.getAllByRole('rowheader')).toHaveLength(2);
});
it('debounces search, paginates results, and resets pagination when cleared', async () => {
  vi.useFakeTimers();
  vi.mocked(apiRequest).mockResolvedValue({ items: [exercise], total: 25 });
  await act(async () => { render(<ExerciseLibrary />); });
  expect(screen.queryByRole('button', { name: 'Shuffle suggestions' })).not.toBeInTheDocument();
  expect(apiRequest).toHaveBeenCalledTimes(1);
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Next' })); });
  expect(apiRequest).toHaveBeenCalledWith('/exercises?q=&page=2&limit=10');
  vi.mocked(apiRequest).mockClear();
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 's' } });
  await act(async () => { vi.advanceTimersByTime(200); });
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'squ' } });
  await act(async () => { vi.advanceTimersByTime(349); });
  expect(apiRequest).not.toHaveBeenCalled();
  await act(async () => { vi.advanceTimersByTime(1); });
  expect(apiRequest).toHaveBeenCalledWith('/exercises?q=squ&page=1&limit=10');
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Next' })); });
  expect(apiRequest).toHaveBeenCalledWith('/exercises?q=squ&page=2&limit=10');
  expect(screen.getByRole('table', { name: 'Exercise library results' })).toBeInTheDocument();
  expect(screen.getAllByRole('columnheader')).toHaveLength(6);
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Clear' })); });
  expect(apiRequest).toHaveBeenLastCalledWith('/exercises?q=&page=1&limit=10');
});
it('ignores an older search response that arrives after the latest query', async () => {
  vi.useFakeTimers();
  let finishOld: ((value: unknown) => void) | undefined;
  vi.mocked(apiRequest).mockImplementation(path => path.includes('q=old&page') ? new Promise(resolve => { finishOld = resolve; }) : Promise.resolve({ items: [exercise], total: 1 }));
  await act(async () => { render(<ExerciseLibrary />); });
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'old' } });
  await act(async () => { vi.advanceTimersByTime(350); });
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'new' } });
  await act(async () => { vi.advanceTimersByTime(350); });
  await act(async () => { finishOld?.({ items: [{ ...exercise, name: 'Stale exercise' }], total: 1 }); });
  expect(screen.queryByText('Stale exercise')).not.toBeInTheDocument();
  expect(screen.getByRole('rowheader', { name: 'Squat' })).toBeInTheDocument();
});
