import '@testing-library/jest-dom/vitest';
import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { apiRequest, type Exercise } from '../../lib/api';
import { ExerciseLibrary } from './exercise-library';
vi.mock('../../lib/api', () => ({ apiRequest: vi.fn() }));
vi.mock('../../components/exercise-gif', () => ({ ExerciseGif: () => <span>Animation</span> }));
afterEach(() => { cleanup(); vi.useRealTimers(); vi.resetAllMocks(); });
const exercise: Exercise = { id: '001', name: 'Squat', target: 'quads', bodyPart: 'legs', equipment: 'body weight', instructions: ['Bend your knees.'], secondaryMuscles: [], gifAvailable: true };
it('debounces typing, shows four clickable suggestions, and resets pagination', async () => {
  vi.useFakeTimers();
  const suggestions = [exercise, ...['Lunge', 'Press', 'Row'].map((name, index) => ({ ...exercise, id: String(index + 2), name }))];
  vi.mocked(apiRequest).mockImplementation(async path => ({ items: path.includes('suggestions') ? suggestions : [exercise], total: 25 }));
  await act(async () => { render(<ExerciseLibrary />); });
  expect(screen.getByRole('button', { name: /Squat legs/ })).toBeInTheDocument();
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Next' })); });
  expect(apiRequest).toHaveBeenCalledWith('/exercises?q=&page=2&limit=10');
  vi.mocked(apiRequest).mockClear();
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 's' } });
  await act(async () => { vi.advanceTimersByTime(200); });
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'squ' } });
  await act(async () => { vi.advanceTimersByTime(349); });
  expect(apiRequest).not.toHaveBeenCalled();
  await act(async () => { vi.advanceTimersByTime(1); });
  expect(apiRequest).toHaveBeenCalledWith('/exercises?q=squ&page=1&limit=10');
  expect(apiRequest).toHaveBeenCalledWith('/exercises/suggestions?q=squ');
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /Lunge legs/ })); });
  expect(apiRequest).toHaveBeenCalledWith('/exercises?q=Lunge&page=1&limit=10');
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Shuffle suggestions' })); });
  expect(apiRequest).toHaveBeenLastCalledWith('/exercises/suggestions?q=Lunge');
});
it('ignores an older search response that arrives after the latest query', async () => {
  vi.useFakeTimers();
  let finishOld: ((value: unknown) => void) | undefined;
  vi.mocked(apiRequest).mockImplementation(path => path.includes('q=old&page') ? new Promise(resolve => { finishOld = resolve; }) : Promise.resolve({ items: path.includes('suggestions') ? [] : [exercise], total: 1 }));
  await act(async () => { render(<ExerciseLibrary />); });
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'old' } });
  await act(async () => { vi.advanceTimersByTime(350); });
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'new' } });
  await act(async () => { vi.advanceTimersByTime(350); });
  await act(async () => { finishOld?.({ items: [{ ...exercise, name: 'Stale exercise' }], total: 1 }); });
  expect(screen.queryByText('Stale exercise')).not.toBeInTheDocument();
  expect(screen.getByRole('heading', { name: 'Squat' })).toBeInTheDocument();
});
