import { useEffect, useState } from 'react';
import { apiRequest, type Exercise } from '../../lib/api';
import { ExerciseGif } from '../../components/exercise-gif';

export function ExerciseLibrary(){
  const[query,setQuery]=useState('');const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[items,setItems]=useState<Exercise[]>([]);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[retry,setRetry]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);setError('');void apiRequest<{items:Exercise[];total:number}>(`/exercises?q=${encodeURIComponent(search)}&page=${page}&limit=10`).then(result=>{if(active){setItems(result.items);setTotal(result.total);}}).catch(error=>{if(active)setError(error instanceof Error?error.message:'Unable to load exercises');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[search,page,retry]);
  return <section className="card collection"><header className="collection-toolbar"><h2>Exercises</h2><form className="collection-tools" onSubmit={event=>{event.preventDefault();setSearch(query);setPage(1);}}><label className="collection-search"><span className="sr-only">Search exercises</span><input type="search" value={query} placeholder="Search exercises…" onChange={event=>setQuery(event.target.value)}/></label><button className="primary">Search</button>{query&&<button className="secondary" type="button" onClick={()=>{setQuery('');setSearch('');setPage(1);}}>Clear</button>}</form></header>{error?<div className="collection-empty" role="alert">{error}<button className="secondary" onClick={()=>setRetry(value=>value+1)}>Try again</button></div>:loading?<p className="collection-empty" role="status">Loading exercises…</p>:items.length?<div className="exercise-grid">{items.map(exercise=><article className="exercise-card" key={exercise.id}><ExerciseGif id={exercise.id} name={exercise.name} available={exercise.gifAvailable}/><div><h3>{exercise.name}</h3><p>{exercise.bodyPart} · {exercise.equipment}</p><details><summary>Instructions</summary><ol>{exercise.instructions.map((step,index)=><li key={index}>{step}</li>)}</ol></details></div></article>)}</div>:<p className="collection-empty">No exercises match your search.</p>}<footer className="collection-pagination"><span>{total} exercises · Page {page} of {Math.max(1,Math.ceil(total/10))}</span><div className="actions"><button className="secondary" disabled={loading||page===1} onClick={()=>setPage(page-1)}>Previous</button><button className="secondary" disabled={loading||page*10>=total} onClick={()=>setPage(page+1)}>Next</button></div></footer></section>;
}
