import '@testing-library/jest-dom/vitest';
import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { apiRequest } from '../../lib/api';
import { ProgramAssignment } from './program-assignment';
import { notify } from '../../lib/notify';
vi.mock('../../lib/notify',()=>({notify:{success:vi.fn(),error:vi.fn()}}));
vi.mock('../../lib/api', () => ({ apiRequest: vi.fn() }));
afterEach(() => { cleanup(); vi.resetAllMocks(); vi.useRealTimers(); });
it('debounces searches, checks assigned clients and immediately saves both toggle directions', async () => {
  vi.useFakeTimers();
  vi.mocked(apiRequest).mockResolvedValueOnce({items:[{id:'sam',name:'Sam',email:'sam@example.test',assignmentId:'existing'}],hasMore:false});
  const onChanged=vi.fn();
  render(<ProgramAssignment programId="program" busy={false} onBusy={vi.fn()} revision={0} onChanged={onChanged}/>);
  expect(apiRequest).not.toHaveBeenCalled();
  fireEvent.change(screen.getByRole('searchbox'),{target:{value:'s'}});
  await act(async()=>{await vi.advanceTimersByTimeAsync(200);});
  fireEvent.change(screen.getByRole('searchbox'),{target:{value:'sam@example.test'}});
  await act(async()=>{await vi.advanceTimersByTimeAsync(349);});
  expect(apiRequest).not.toHaveBeenCalled();
  await act(async()=>{await vi.advanceTimersByTimeAsync(1);});
  expect(apiRequest).toHaveBeenCalledExactlyOnceWith('/coach/programs/assignment-clients?programId=program&q=sam%40example.test');
  const checkbox=screen.getByRole('checkbox');
  expect(checkbox).toBeChecked();
  vi.mocked(apiRequest).mockResolvedValueOnce(undefined);
  await act(async()=>{fireEvent.click(checkbox);});
  expect(apiRequest).toHaveBeenLastCalledWith('/coach/programs/program/assignments/existing',{method:'DELETE'});
  expect(checkbox).not.toBeChecked();
  vi.mocked(apiRequest).mockResolvedValueOnce({assignments:[{id:'new'}]});
  await act(async()=>{fireEvent.click(checkbox);});
  expect(apiRequest).toHaveBeenLastCalledWith('/coach/programs/program/assign',{method:'POST',body:JSON.stringify({clientIds:['sam']})});
  expect(checkbox).toBeChecked();
  expect(onChanged).toHaveBeenCalledTimes(2);
  vi.mocked(apiRequest).mockRejectedValueOnce(new Error('Unable to save'));
  await act(async()=>{fireEvent.click(checkbox);});
  expect(checkbox).toBeChecked();
  expect(notify.error).toHaveBeenCalledWith('Unable to save');
  expect(onChanged).toHaveBeenCalledTimes(2);
});
it('ignores stale responses and refreshes checked state after an external removal', async()=>{
  vi.useFakeTimers();
  let resolveOld!: (value: unknown)=>void;
  vi.mocked(apiRequest).mockImplementationOnce(()=>new Promise(resolve=>{resolveOld=resolve;})).mockResolvedValueOnce({items:[{id:'sam',name:'Sam',email:'sam@example.test',assignmentId:'a'}],hasMore:false});
  const props={programId:'p',busy:false,onBusy:vi.fn(),onChanged:vi.fn()};
  const {rerender}=render(<ProgramAssignment {...props} revision={0}/>);
  fireEvent.change(screen.getByRole('searchbox'),{target:{value:'old'}});
  await act(async()=>{await vi.advanceTimersByTimeAsync(350);});
  fireEvent.change(screen.getByRole('searchbox'),{target:{value:'Sam'}});
  await act(async()=>{await vi.advanceTimersByTimeAsync(350);resolveOld({items:[],hasMore:false});});
  expect(screen.getByRole('checkbox')).toBeChecked();
  vi.mocked(apiRequest).mockResolvedValueOnce({items:[{id:'sam',name:'Sam',email:'sam@example.test',assignmentId:null}],hasMore:false});
  rerender(<ProgramAssignment {...props} revision={1}/>);
  await act(async()=>{await vi.advanceTimersByTimeAsync(350);});
  expect(screen.getByRole('checkbox')).not.toBeChecked();
});
