import { useCallback, useEffect, useState } from 'react';
import { Navigate } from 'react-router-dom';
import { apiRequest, type AdminOverview, type AuditEvent, type User } from '../../lib/api';
import { useAuth } from '../auth/auth-context';

type Filter = 'ALL' | User['approvalStatus'];

export function AdminDashboard() {
  const { user, ready } = useAuth();
  const [coaches, setCoaches] = useState<User[]>([]); const [overview, setOverview] = useState<AdminOverview | null>(null); const [events, setEvents] = useState<AuditEvent[]>([]);
  const [filter, setFilter] = useState<Filter>('ALL'); const [tab, setTab] = useState<'coaches' | 'audit'>('coaches'); const [error, setError] = useState(''); const [busyId, setBusyId] = useState(''); const [resetCode, setResetCode] = useState('');
  const load = useCallback(async () => { try { const [coachResult, overviewResult, auditResult] = await Promise.all([apiRequest<{ coaches: User[] }>('/admin/coaches'), apiRequest<{ overview: AdminOverview }>('/admin/overview'), apiRequest<{ events: AuditEvent[] }>('/admin/audit-events')]); setCoaches(coachResult.coaches); setOverview(overviewResult.overview); setEvents(auditResult.events); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load admin workspace'); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (!ready) return <p>Loading session…</p>; if (!user) return <Navigate to="/login" replace />; if (user.role !== 'PLATFORM_ADMIN') return <Navigate to="/" replace />;

  async function transition(coach: User, action: 'approve' | 'reject' | 'suspend' | 'reopen') { const needsReason = action === 'reject' || action === 'suspend'; const reason = needsReason ? window.prompt(`Reason to ${action} this coach?`) : null; if (needsReason && !reason) return; setBusyId(coach.id); setError(''); try { await apiRequest(`/admin/coaches/${coach.id}/${action}`, { method: 'POST', body: JSON.stringify(reason ? { reason } : {}) }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to update coach'); } finally { setBusyId(''); } }
  async function issueReset(coach: User) { setBusyId(coach.id); setError(''); try { const result = await apiRequest<{ reset: { token: string } }>(`/admin/users/${coach.id}/password-reset`, { method: 'POST', body: '{}' }); setResetCode(result.reset.token); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to issue reset'); } finally { setBusyId(''); } }
  const visible = filter === 'ALL' ? coaches : coaches.filter((coach) => coach.approvalStatus === filter);
  return <section><div className="dashboard-head"><div><p className="eyebrow">Platform control</p><h1>Admin dashboard</h1><p className="lede">Approve coaches, protect access, and review every sensitive change.</p></div><button className="secondary" onClick={() => void load()}>Refresh data</button></div>
    {error && <p className="error" role="alert">{error}</p>}
    <div className="dashboard-grid"><Metric label="Total coaches" value={overview?.totalCoaches} /><Metric label="Awaiting review" value={overview?.pendingCoaches} accent /><Metric label="Approved coaches" value={overview?.approvedCoaches} /><Metric label="Suspended" value={overview?.suspendedCoaches} /><Metric label="Total clients" value={overview?.totalClients} /><Metric label="Pending clients" value={overview?.pendingClients} /></div>
    <div className="tabs"><button className={tab === 'coaches' ? 'active' : ''} onClick={() => setTab('coaches')}>Coach management</button><button className={tab === 'audit' ? 'active' : ''} onClick={() => setTab('audit')}>Security audit</button></div>
    {resetCode && <div className="card reset-code"><div><strong>One-time reset code</strong><p>Shown once and valid for 30 minutes.</p></div><input readOnly value={resetCode} aria-label="One-time reset code" /><button className="secondary" onClick={() => setResetCode('')}>Close</button></div>}
    {tab === 'coaches' ? <div className="card table-card"><div className="table-title"><div><h2>Coach accounts</h2><span>{visible.length} shown</span></div><select value={filter} onChange={(event) => setFilter(event.target.value as Filter)}><option value="ALL">All statuses</option><option value="PENDING_REVIEW">Pending</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="SUSPENDED">Suspended</option></select></div><div className="coach-list">{visible.map((coach) => <article className="coach-row" key={coach.id}><div className="avatar">{coach.displayName[0]?.toUpperCase()}</div><div className="coach-main"><strong>{coach.displayName}</strong><span>{coach.businessName}</span></div><div className="coach-contact"><span>{coach.email}</span><small>Joined {new Date(coach.createdAt).toLocaleDateString()}</small></div><span className={`status ${coach.approvalStatus.toLowerCase()}`}>{coach.approvalStatus.replace('_', ' ')}</span><div className="actions"><button className="secondary" disabled={busyId === coach.id} onClick={() => void issueReset(coach)}>Reset</button>{coach.approvalStatus === 'PENDING_REVIEW' && <><button className="danger" onClick={() => void transition(coach, 'reject')}>Reject</button><button className="primary small" onClick={() => void transition(coach, 'approve')}>Approve</button></>}{coach.approvalStatus === 'APPROVED' && <button className="danger" onClick={() => void transition(coach, 'suspend')}>Suspend</button>}{coach.approvalStatus === 'SUSPENDED' && <button className="primary small" onClick={() => void transition(coach, 'approve')}>Restore</button>}{coach.approvalStatus === 'REJECTED' && <button className="secondary" onClick={() => void transition(coach, 'reopen')}>Reopen</button>}</div></article>)}{visible.length === 0 && <div className="empty"><h3>No matching coaches</h3><p>Try another status filter.</p></div>}</div></div> : <div className="card table-card"><div className="table-title"><div><h2>Recent security activity</h2><span>Latest 100 events</span></div></div><div className="audit-list">{events.map((event) => <article className="audit-row" key={event.id}><span className="audit-icon">✓</span><div><strong>{event.action.replaceAll('_', ' ')}</strong><p>{event.actorEmail ?? 'System'} → {event.subjectEmail ?? event.entityId}</p></div><time>{new Date(event.createdAt).toLocaleString()}</time></article>)}{events.length === 0 && <div className="empty"><h3>No activity yet</h3></div>}</div></div>}
  </section>;
}

function Metric({ label, value, accent = false }: { label: string; value: number | undefined; accent?: boolean }) { return <div className={`card metric-card ${accent ? 'accent' : ''}`}><span>{label}</span><strong>{value ?? '—'}</strong></div>; }
