import sharp from 'sharp';
import 'dotenv/config';
import { randomBytes, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import express from 'express';
import pg from 'pg';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { validateEnvironment } from '../../config/environment.js';
import { issueAccessToken } from '../identity/auth.js';
import { createMvpRouter } from './router.js';
import { dateSchema, definitionSchema, dueDates, flagsFor, validateAnswers } from './checkin-model.js';

const definition = definitionSchema.parse({name:'Weekly review',fields:[{id:'weight',label:'Weight',type:'NUMBER',required:true,min:1,max:500,unit:'kg',metric:true},{id:'stress',label:'Stress',type:'RATING',required:true,min:1,max:10,metric:true,flag:{operator:'GT',value:5}},{id:'notes',label:'Notes',type:'LONG_TEXT',required:false}]});
it('validates typed answers, required submissions and attention rules',()=>{
  expect(validateAnswers(definition,{},false)).toEqual({});
  expect(()=>validateAnswers(definition,{},true)).toThrow('Weight is required');
  expect(()=>validateAnswers(definition,{weight:'70',stress:4},true)).toThrow();
  expect(()=>validateAnswers(definition,{weight:70,stress:4.5},true)).toThrow();
  expect(()=>validateAnswers(definition,{unknown:1},false)).toThrow();
  expect(flagsFor(definition,{weight:70,stress:7})).toEqual([{id:'stress',label:'Stress',value:7}]);
  expect(definitionSchema.safeParse({...definition,fields:[definition.fields[0],definition.fields[0]]}).success).toBe(false);
});
it('generates bounded calendar dates with month-end and leap-year handling',()=>{
  expect(dueDates('2028-01-31','MONTHLY',3)).toEqual(['2028-01-31','2028-02-29','2028-03-31']);
  expect(dueDates('2026-09-13','BIWEEKLY',2)).toEqual(['2026-09-13','2026-09-27']);
  expect(dateSchema.safeParse('2026-02-30').success).toBe(false);
});

describe.skipIf(!process.env.DATABASE_URL)('check-in storage and authorization',()=>{
  const schema=`checkin_test_${randomUUID().replaceAll('-','')}`;
  const admin=new pg.Pool({connectionString:process.env.DATABASE_URL});
  const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,options:`-c search_path=${schema},public`});
  const env=validateEnvironment({DATABASE_URL:process.env.DATABASE_URL??'postgresql://localhost/unused',JWT_ACCESS_SECRET:randomBytes(32).toString('hex'),NODE_ENV:'test'});
  const coach=randomUUID(), other=randomUUID(), person=randomUUID(), stranger=randomUUID();
  const token=(id:string,role:'COACH'|'CLIENT')=>`Bearer ${issueAccessToken(env,{id,role})}`;
  const app=express();app.use(express.json());app.use(createMvpRouter(env,pool));
  const coachToken=token(coach,'COACH'), clientToken=token(person,'CLIENT');
  beforeAll(async()=>{
    await admin.query(`CREATE SCHEMA ${schema}`);
    for(const file of ['001_identity_approvals.sql','002_demo_mvp.sql','003_nutrition_library.sql'])await pool.query(await readFile(new URL(`../../../db/migrations/${file}`,import.meta.url),'utf8'));
    for(const [id,role] of [[coach,'COACH'],[other,'COACH'],[person,'CLIENT'],[stranger,'CLIENT']]){
      await pool.query("INSERT INTO users(id,email,password_hash,role,account_status) VALUES($1,$2,'unused-test-hash',$3,'APPROVED')",[id,`${id}@example.test`,role]);
      if(role==='COACH')await pool.query("INSERT INTO coach_profiles(user_id,display_name,business_name) VALUES($1,'Test coach','Test business')",[id]);
    }
    await pool.query("INSERT INTO coach_clients(coach_id,client_id,status) VALUES($1,$2,'APPROVED')",[coach,person]);
    const legacy=await pool.query<{id:string}>("INSERT INTO checkin_assignments(coach_id,client_id,due_date) VALUES($1,$2,'2026-09-01') RETURNING id",[coach,person]);
    await pool.query("INSERT INTO checkin_submissions(assignment_id,coach_id,client_id,data,status,submitted_snapshot) VALUES($1,$2,$3,$4,'SUBMITTED',$4)",[legacy.rows[0]!.id,coach,person,JSON.stringify({currentWeight:70})]);
    await pool.query(await readFile(new URL('../../../db/migrations/004_checkin_forms.sql',import.meta.url),'utf8'));
    await pool.query(await readFile(new URL('../../../db/migrations/005_daily_checkin_photos.sql',import.meta.url),'utf8'));
    const migrated=await pool.query<{form_snapshot:{fields:Array<{id:string}>}}>('SELECT form_snapshot FROM checkin_assignments WHERE id=$1',[legacy.rows[0]!.id]);
    expect(migrated.rows[0]!.form_snapshot.fields.some(field=>field.id==='currentWeight')).toBe(true);
    expect((await pool.query('SELECT id FROM checkin_logs WHERE assignment_id=$1',[legacy.rows[0]!.id])).rowCount).toBe(1);
  },30000);
  afterAll(async()=>{await pool.end();await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin.end();});
  it('prevents duplicate dates across schedules and rescheduling while allowing different forms',async()=>{
    const makeForm=async()=>((await request(app).post('/coach/checkins/forms').set('Authorization',coachToken).send({definition})).body as {form:{id:string}}).form.id;
    const formId=await makeForm();
    const assign=(extra:object={})=>request(app).post('/coach/checkins').set('Authorization',coachToken).send({formId,clientIds:[person],dueDate:'2027-01-01',frequency:'WEEKLY',occurrences:2,...extra});
    const responses=await Promise.all([assign(),assign()]);
    expect(responses.map(result=>result.status).sort()).toEqual([201,409]);
    const ids=(responses.find(result=>result.status===201)!.body as {assignmentIds:string[]}).assignmentIds;
    expect((await pool.query<{date:string}>('SELECT due_date::text date FROM checkin_assignments WHERE id=ANY($1::uuid[]) ORDER BY due_date',[ids])).rows.map(row=>row.date)).toEqual(['2027-01-01','2027-01-08']);
    expect((await assign({dueDate:'2026-12-25',occurrences:3})).status).toBe(409);
    expect((await pool.query('SELECT id FROM checkin_assignments WHERE form_id=$1',[formId])).rowCount).toBe(2);
    expect((await request(app).post(`/coach/checkins/${ids[1]!}/reschedule`).set('Authorization',coachToken).send({previousDate:'2027-01-08',dueDate:'2027-01-01'})).status).toBe(409);
    expect((await request(app).post(`/coach/checkins/${ids[1]!}/reschedule`).set('Authorization',coachToken).send({previousDate:'2027-01-08',dueDate:'2027-01-09'})).status).toBe(200);
    expect((await assign({formId:await makeForm(),frequency:'ONCE',occurrences:30})).status).toBe(201);
    expect((await pool.query('SELECT id FROM checkin_assignments WHERE client_id=$1 AND due_date=$2',[person,'2027-01-01'])).rowCount).toBe(2);
  },30000);
  it('preserves versions, drafts, snapshots and review history with atomic audits',async()=>{
    expect((await request(app).get('/coach/checkins')).status).toBe(401);
    expect((await request(app).post('/coach/checkins/forms').set('Authorization',clientToken).send({definition})).status).toBe(403);
    const created=await request(app).post('/coach/checkins/forms').set('Authorization',coachToken).send({definition,isDefault:true});
    expect(created.status).toBe(201);
    const form=(created.body as {form:{id:string;version:number}}).form;
    expect((await request(app).put(`/coach/checkins/forms/${form.id}`).set('Authorization',token(other,'COACH')).send({definition,version:1})).status).toBe(404);
    const assigned=await request(app).post('/coach/checkins').set('Authorization',coachToken).send({clientIds:[person],dueDate:'2026-09-13',frequency:'DAILY',occurrences:2});
    expect(assigned.status).toBe(201);
    const ids=(assigned.body as {assignmentIds:string[]}).assignmentIds;
    const id=ids[0]!;
    expect(ids).toHaveLength(2);
    expect((await pool.query<{date:string}>('SELECT due_date::text date FROM checkin_assignments WHERE id=ANY($1::uuid[]) ORDER BY due_date',[ids])).rows.map(row=>row.date)).toEqual(['2026-09-13','2026-09-14']);
    expect((await request(app).post('/coach/checkins').set('Authorization',coachToken).send({formId:form.id,clientIds:[stranger],dueDate:'2026-09-13'})).status).toBe(404);
    expect((await request(app).put(`/coach/checkins/forms/${form.id}`).set('Authorization',coachToken).send({definition:{...definition,name:'Updated form'},version:1})).status).toBe(200);
    expect((await pool.query<{form_snapshot:{name:string}}>('SELECT form_snapshot FROM checkin_assignments WHERE id=$1',[id])).rows[0]!.form_snapshot.name).toBe('Weekly review');
    expect((await request(app).put(`/client/checkins/${id}`).set('Authorization',token(stranger,'CLIENT')).send({revision:0,answers:{}})).status).toBe(404);
    expect((await request(app).put(`/client/checkins/${id}`).set('Authorization',clientToken).send({revision:0,answers:{weight:70}})).status).toBe(200);
    expect((await request(app).put(`/client/checkins/${id}`).set('Authorization',clientToken).send({revision:0,answers:{weight:75}})).status).toBe(409);
    expect((await request(app).post(`/client/checkins/${id}/submit`).set('Authorization',clientToken).send({revision:1,answers:{weight:70}})).status).toBe(400);
    const image=await sharp({create:{width:10,height:10,channels:3,background:'#008844'}}).png().toBuffer();
    expect((await request(app).post(`/client/checkins/${id}/submit`).set('Authorization',clientToken).send({revision:1,answers:{weight:71,stress:7}})).status).toBe(400);
    expect((await request(app).post(`/client/checkins/${id}/photos`).set('Authorization',clientToken).set('Content-Type','application/octet-stream').send(Buffer.from('<svg></svg>'))).status).toBe(400);
    expect((await request(app).post(`/client/checkins/${id}/photos`).set('Authorization',token(stranger,'CLIENT')).set('Content-Type','application/octet-stream').send(image)).status).toBe(404);
    await pool.query("ALTER TABLE audit_events ADD CONSTRAINT fail_photo CHECK(action <> 'CHECKIN_PHOTO_ADDED') NOT VALID");
    expect((await request(app).post(`/client/checkins/${id}/photos`).set('Authorization',clientToken).set('Content-Type','application/octet-stream').send(image)).status).toBe(500);
    expect((await pool.query('SELECT id FROM checkin_photos WHERE assignment_id=$1',[id])).rowCount).toBe(0);
    await pool.query('ALTER TABLE audit_events DROP CONSTRAINT fail_photo');
    const upload=await request(app).post(`/client/checkins/${id}/photos`).set('Authorization',clientToken).set('Content-Type','application/octet-stream').send(image);
    expect(upload.status).toBe(201);
    const photoId=(upload.body as {photo:{id:string}}).photo.id;
    const fetched=await request(app).get(`/coach/checkins/${id}/photos/${photoId}`).set('Authorization',coachToken);
    expect(fetched.status).toBe(200);expect(fetched.headers['content-type']).toContain('image/jpeg');expect(fetched.headers['cache-control']).toContain('no-store');
    expect((await request(app).get(`/coach/checkins/${id}/photos/${photoId}`).set('Authorization',token(other,'COACH'))).status).toBe(404);
    expect((await request(app).get(`/client/checkins/${id}/photos/${photoId}`)).status).toBe(401);
    expect((await request(app).post(`/client/checkins/${id}/submit`).set('Authorization',clientToken).send({revision:1,answers:{weight:71,stress:7,notes:'A busy week'}})).status).toBe(200);
    expect((await request(app).delete(`/client/checkins/${id}/photos/${photoId}`).set('Authorization',clientToken)).status).toBe(409);
    expect((await request(app).post(`/client/checkins/${id}/photos`).set('Authorization',clientToken).set('Content-Type','application/octet-stream').send(image)).status).toBe(409);
    expect((await request(app).put(`/client/checkins/${id}`).set('Authorization',clientToken).send({revision:2,answers:{weight:72}})).status).toBe(409);
    const row=(await pool.query<{submitted_snapshot:{weight:number};flags:unknown[]}>('SELECT submitted_snapshot,flags FROM checkin_submissions WHERE assignment_id=$1',[id])).rows[0]!;
    expect(row.submitted_snapshot.weight).toBe(71);expect(row.flags).toHaveLength(1);
    await pool.query("ALTER TABLE audit_events ADD CONSTRAINT fail_review CHECK(action <> 'CHECKIN_REVIEWED') NOT VALID");
    expect((await request(app).post(`/coach/checkins/${id}/review`).set('Authorization',coachToken).send({revision:2,status:'NEEDS_ATTENTION',notes:'Let us discuss recovery'})).status).toBe(500);
    expect((await pool.query<{status:string}>('SELECT status FROM checkin_submissions WHERE assignment_id=$1',[id])).rows[0]!.status).toBe('SUBMITTED');
    await pool.query('ALTER TABLE audit_events DROP CONSTRAINT fail_review');
    expect((await request(app).post(`/coach/checkins/${id}/review`).set('Authorization',coachToken).send({revision:2,status:'NEEDS_ATTENTION',notes:'Let us discuss recovery'})).status).toBe(200);
    expect((await request(app).post(`/coach/checkins/${id}/review`).set('Authorization',coachToken).send({revision:2,status:'NEUTRAL'})).status).toBe(409);
    const history=await request(app).get(`/coach/checkins/${id}/history`).set('Authorization',coachToken);
    expect((history.body as {history:unknown[]}).history).toHaveLength(5);
    expect((await request(app).get(`/coach/checkins/${id}/history`).set('Authorization',token(other,'COACH'))).status).toBe(404);
    await pool.query("UPDATE coach_clients SET status='SUSPENDED' WHERE client_id=$1",[person]);
    expect((await request(app).get('/client/checkins').set('Authorization',clientToken)).body).toEqual({checkins:[]});
    expect((await request(app).put(`/client/checkins/${ids[1]!}`).set('Authorization',clientToken).send({revision:0,answers:{}})).status).toBe(404);
  },30000);
});
