import { createCoachCheckins, createClientCheckins } from './checkins.js';
import { createNutritionCoachRouter, createNutritionClientRouter } from './nutrition.js';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { Router, type NextFunction, type Response } from 'express';
import type { Pool, PoolClient } from 'pg';
import { z } from 'zod';
import type { Environment } from '../../config/environment.js';
import { authenticate, type AuthenticatedRequest } from '../identity/auth.js';
import { exerciseGifFilename, isGifSignature } from './exercise-assets.js';

/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-return -- pg query rows are validated or serialized at the HTTP boundary */

const uuid=z.string().uuid();const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);const optionalNumber=z.number().nonnegative().nullable().optional();
const onboarding=z.object({personalDetails:z.string().min(2).max(1000),fitnessGoal:z.string().min(2).max(500),experienceLevel:z.enum(['BEGINNER','INTERMEDIATE','ADVANCED']),height:z.number().positive().max(300),weight:z.number().positive().max(1000),injuries:z.string().max(2000),availableEquipment:z.array(z.string().max(100)).max(50),preferredTrainingDays:z.array(z.string().max(20)).max(7),nutritionPreferences:z.string().max(2000),additionalNotes:z.string().max(4000)});
const template=z.object({name:z.string().trim().min(2).max(150),description:z.string().max(2000).default(''),exercises:z.array(z.object({exerciseId:z.string().regex(/^[0-9A-Za-z_-]+$/),sets:z.number().int().positive().max(100),repetitions:z.number().int().nonnegative().nullable().optional(),durationSeconds:z.number().int().nonnegative().nullable().optional(),restSeconds:z.number().int().nonnegative().max(3600).default(60),targetRpe:z.number().min(0).max(10).nullable().optional(),tempo:z.string().max(50).nullable().optional(),notes:z.string().max(1000).nullable().optional()})).min(1).max(100)});
const program=z.object({name:z.string().trim().min(2).max(150),description:z.string().max(2000).default(''),days:z.array(z.object({templateId:uuid,dayLabel:z.string().trim().min(1).max(100)})).min(1).max(100)});
const nutrition=z.object({clientId:uuid,dailyCalories:z.number().int().nonnegative(),proteinGrams:z.number().int().nonnegative(),carbohydrateGrams:z.number().int().nonnegative(),fatGrams:z.number().int().nonnegative(),mealGuidance:z.string().max(4000),notes:z.string().max(4000),startsOn:date,endsOn:date.nullable().optional()});
const nutritionLog=z.object({logDate:date,calories:z.number().int().nonnegative(),proteinGrams:z.number().int().nonnegative(),carbohydrateGrams:z.number().int().nonnegative(),fatGrams:z.number().int().nonnegative(),notes:z.string().max(4000)});
const progress=z.object({measurementDate:date,bodyWeight:optionalNumber,waist:optionalNumber,chest:optionalNumber,arm:optionalNumber,notes:z.string().max(4000)});
const subscription=z.object({clientId:uuid,planName:z.string().trim().min(2).max(150),status:z.enum(['PENDING','ACTIVE','PAUSED','CANCELLED','EXPIRED']),startsOn:date,endsOrRenewsOn:date.nullable().optional(),amount:z.number().nonnegative().nullable().optional(),currency:z.string().length(3).nullable().optional(),notes:z.string().max(4000)});

export function createMvpRouter(environment:Environment,pool:Pool):Router{const router=Router();const jwt=authenticate(environment);const auth=(request:AuthenticatedRequest,response:Response,next:NextFunction)=>jwt(request,response,()=>{void pool.query<{role:string;account_status:string}>('SELECT role,account_status FROM users WHERE id=$1',[request.auth?.userId]).then(result=>{const row=result.rows[0];if(!row||row.account_status!=='APPROVED'){response.status(403).json({code:'FORBIDDEN',message:'Approved account required'});return;}request.auth={userId:request.auth!.userId,role:row.role as 'PLATFORM_ADMIN'|'COACH'|'CLIENT',approvalStatus:'APPROVED'};next();}).catch(next);});
  const role=(expected:'COACH'|'CLIENT')=>(request:AuthenticatedRequest,response:Response,next:NextFunction)=>request.auth?.role===expected?next():response.status(403).json({code:'FORBIDDEN',message:'You do not have access to this resource'});
  router.use('/coach/checkins',auth,role('COACH'),createCoachCheckins(pool));
  router.use('/client/checkins',auth,role('CLIENT'),createClientCheckins(pool));
  router.use('/coach/nutrition-library',auth,role('COACH'),createNutritionCoachRouter(pool));
  router.use('/client/nutrition-plan',auth,role('CLIENT'),createNutritionClientRouter(pool));
  router.get('/exercises',auth,async(request,response)=>{const page=Math.max(1,Number(request.query.page)||1);const limit=Math.min(50,Math.max(1,Number(request.query.limit)||20));const q=typeof request.query.q==='string'?request.query.q.trim():'';const bodyPart=typeof request.query.bodyPart==='string'?request.query.bodyPart:'';const equipment=typeof request.query.equipment==='string'?request.query.equipment:'';const target=typeof request.query.target==='string'?request.query.target:'';const values:unknown[]=[];const clauses:string[]=[];for(const [column,value] of [['name',q],['body_part',bodyPart],['equipment',equipment],['target',target]])if(value){values.push(column==='name'?`%${value}%`:value);clauses.push(column==='name'?`name ILIKE $${values.length}`:`${column}=$${values.length}`);}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const count=await pool.query<{count:string}>(`SELECT count(*) FROM exercises ${where}`,values);values.push(limit,(page-1)*limit);const result=await pool.query(`SELECT external_id "id",name,body_part "bodyPart",equipment,target,secondary_muscles "secondaryMuscles",instructions,gif_available "gifAvailable" FROM exercises ${where} ORDER BY name LIMIT $${values.length-1} OFFSET $${values.length}`,values);response.json({items:result.rows,page,limit,total:Number(count.rows[0]?.count??0)});});
  router.get('/exercises/filters',auth,async(_request,response)=>{const [body,equipment,target]=await Promise.all([pool.query('SELECT DISTINCT body_part value FROM exercises ORDER BY value'),pool.query('SELECT DISTINCT equipment value FROM exercises ORDER BY value'),pool.query('SELECT DISTINCT target value FROM exercises ORDER BY value')]);response.json({bodyParts:body.rows.map(r=>r.value),equipment:equipment.rows.map(r=>r.value),targets:target.rows.map(r=>r.value)});});
  const exerciseGif=async(request:AuthenticatedRequest,response:Response)=>{const id=typeof request.params.id==='string'?request.params.id:'';let filename:string;try{filename=exerciseGifFilename(id);}catch{response.status(400).send();return;}const result=await pool.query<{gif_available:boolean}>('SELECT gif_available FROM exercises WHERE external_id=$1',[id]);if(!result.rows[0]?.gif_available){if(environment.NODE_ENV==='development')console.warn(`Missing exercise GIF: ${id}`);response.status(404).json({code:'MEDIA_MISSING',message:'Exercise animation unavailable'});return;}try{const bytes=await readFile(resolve(process.cwd(),'../../exercise_images',filename));if(!isGifSignature(bytes)){response.status(415).send();return;}response.type('image/gif').set({'Cache-Control':'public, max-age=86400','Cross-Origin-Resource-Policy':'cross-origin'}).send(bytes);}catch{response.status(404).send();}};
  router.get('/exercise-media/:id',exerciseGif);router.get('/exercises/:id/gif',exerciseGif);

  router.get('/client/onboarding',auth,role('CLIENT'),async(request,response)=>{const result=await pool.query('SELECT id,status,data,submitted_at "submittedAt",reviewed_at "reviewedAt" FROM onboarding_submissions WHERE client_id=$1',[request.auth!.userId]);response.json({onboarding:result.rows[0]??null});});
  router.put('/client/onboarding',auth,role('CLIENT'),async(request,response)=>{const parsed=onboarding.safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);const tenant=await clientTenant(pool,request.auth!.userId);if(!tenant)return response.status(409).json({code:'NO_COACH',message:'Approved coach relationship required'});const result=await pool.query(`INSERT INTO onboarding_submissions(coach_id,client_id,data) VALUES($1,$2,$3) ON CONFLICT(coach_id,client_id) DO UPDATE SET data=excluded.data,updated_at=now() WHERE onboarding_submissions.status='DRAFT' RETURNING id,status,data`,[tenant.coachId,request.auth!.userId,parsed.data]);if(!result.rows[0])return response.status(409).json({code:'ALREADY_SUBMITTED',message:'Submitted onboarding cannot be changed'});return response.json({onboarding:result.rows[0]});});
  router.post('/client/onboarding/submit',auth,role('CLIENT'),async(request,response)=>{const result=await pool.query(`UPDATE onboarding_submissions SET status='SUBMITTED',submitted_snapshot=data,submitted_at=now(),updated_at=now() WHERE client_id=$1 AND status='DRAFT' RETURNING id,status,submitted_at "submittedAt"`,[request.auth!.userId]);return result.rows[0]?response.json({onboarding:result.rows[0]}):response.status(409).json({code:'INVALID_TRANSITION',message:'Save a draft before submitting'});});
  router.get('/coach/clients/:clientId/onboarding',auth,role('COACH'),async(request,response)=>{const clientId=param(request,'clientId');if(!await owns(pool,request.auth!.userId,clientId))return response.status(404).json({code:'NOT_FOUND',message:'Client not found'});const result=await pool.query(`SELECT id,status,COALESCE(submitted_snapshot,data) data,submitted_at "submittedAt",reviewed_at "reviewedAt" FROM onboarding_submissions WHERE coach_id=$1 AND client_id=$2`,[request.auth!.userId,clientId]);return response.json({onboarding:result.rows[0]??null});});
  router.post('/coach/clients/:clientId/onboarding/review',auth,role('COACH'),async(request,response)=>{const clientId=param(request,'clientId');const result=await pool.query(`UPDATE onboarding_submissions SET status='REVIEWED',reviewed_at=now(),reviewed_by_user_id=$1,updated_at=now() WHERE coach_id=$1 AND client_id=$2 AND status='SUBMITTED' RETURNING id,status,reviewed_at "reviewedAt"`,[request.auth!.userId,clientId]);return result.rows[0]?response.json({onboarding:result.rows[0]}):response.status(404).json({code:'NOT_FOUND',message:'Submitted onboarding not found'});});

  router.get('/coach/workout-templates',auth,role('COACH'),async(request,response)=>response.json({templates:(await pool.query(`SELECT wt.*,COALESCE(json_agg(json_build_object('id',wte.id,'exerciseId',wte.exercise_external_id,'name',e.name,'position',wte.position,'sets',wte.sets,'repetitions',wte.repetitions,'durationSeconds',wte.duration_seconds,'restSeconds',wte.rest_seconds,'targetRpe',wte.target_rpe,'tempo',wte.tempo,'notes',wte.notes) ORDER BY wte.position) FILTER(WHERE wte.id IS NOT NULL),'[]') exercises FROM workout_templates wt LEFT JOIN workout_template_exercises wte ON wte.template_id=wt.id LEFT JOIN exercises e ON e.external_id=wte.exercise_external_id WHERE wt.coach_id=$1 GROUP BY wt.id ORDER BY wt.created_at DESC`,[request.auth!.userId])).rows}));
  router.post('/coach/workout-templates',auth,role('COACH'),async(request,response)=>saveTemplate(pool,request,response));router.put('/coach/workout-templates/:id',auth,role('COACH'),async(request,response)=>saveTemplate(pool,request,response,param(request,'id')));
  router.delete('/coach/workout-templates/:id',auth,role('COACH'),async(request,response)=>{if(!uuid.safeParse(param(request,'id')).success)return response.status(400).json({message:'Invalid workout'});const result=await tx(pool,async c=>{const row=(await c.query<{id:string}>('UPDATE workout_templates SET archived_at=now(),updated_at=now() WHERE id=$1 AND coach_id=$2 AND archived_at IS NULL RETURNING id',[param(request,'id'),request.auth!.userId])).rows[0];if(row)await c.query("INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id) VALUES($1,'WORKOUT_ARCHIVED','WORKOUT',$2)",[request.auth!.userId,row.id]);return row;});return result?response.status(204).send():response.status(404).json({message:'Workout not found'});});
  router.delete('/coach/programs/:id',auth,role('COACH'),async(request,response)=>{if(!uuid.safeParse(param(request,'id')).success)return response.status(400).json({message:'Invalid program'});const result=await tx(pool,async c=>{const row=(await c.query<{id:string}>("UPDATE programs SET status='ARCHIVED',updated_at=now() WHERE id=$1 AND coach_id=$2 AND status<>'ARCHIVED' RETURNING id",[param(request,'id'),request.auth!.userId])).rows[0];if(row)await c.query("INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id) VALUES($1,'PROGRAM_ARCHIVED','PROGRAM',$2)",[request.auth!.userId,row.id]);return row;});return result?response.status(204).send():response.status(404).json({message:'Program not found'});});
  router.get('/coach/programs',auth,role('COACH'),async(request,response)=>response.json({programs:(await pool.query(`SELECT p.*,COALESCE(json_agg(json_build_object('id',pd.id,'templateId',pd.template_id,'dayLabel',pd.day_label,'position',pd.position,'templateName',wt.name) ORDER BY pd.position) FILTER(WHERE pd.id IS NOT NULL),'[]') days FROM programs p LEFT JOIN program_days pd ON pd.program_id=p.id LEFT JOIN workout_templates wt ON wt.id=pd.template_id WHERE p.coach_id=$1 GROUP BY p.id ORDER BY p.created_at DESC`,[request.auth!.userId])).rows}));
  router.post('/coach/programs',auth,role('COACH'),async(request,response)=>saveProgram(pool,request,response));router.put('/coach/programs/:id',auth,role('COACH'),async(request,response)=>saveProgram(pool,request,response,param(request,'id')));
  router.post('/coach/programs/:id/publish',auth,role('COACH'),async(request,response)=>{const result=await tx(pool,async c=>(await c.query(`UPDATE programs SET status='PUBLISHED',published_at=now(),updated_at=now() WHERE id=$1 AND coach_id=$2 AND status='DRAFT' AND EXISTS(SELECT 1 FROM program_days WHERE program_id=$1) RETURNING *`,[param(request,'id'),request.auth!.userId])).rows[0]);return result?response.json({program:result}):response.status(409).json({code:'INVALID_PROGRAM',message:'Only a complete draft can be published'});});
  router.post('/coach/programs/:id/assign',auth,role('COACH'),async(request,response)=>{const parsed=z.object({clientId:uuid}).safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);if(!await owns(pool,request.auth!.userId,parsed.data.clientId))return response.status(404).json({code:'NOT_FOUND',message:'Approved client not found'});const assignment=await tx(pool,async c=>{const p=await programSnapshot(c,param(request,'id'),request.auth!.userId);if(!p)throw new Error('PROGRAM_NOT_PUBLISHED');await c.query('UPDATE program_assignments SET active=false WHERE coach_id=$1 AND client_id=$2 AND active=true',[request.auth!.userId,parsed.data.clientId]);return(await c.query('INSERT INTO program_assignments(coach_id,client_id,program_id,snapshot) VALUES($1,$2,$3,$4) RETURNING id,assigned_at "assignedAt"',[request.auth!.userId,parsed.data.clientId,param(request,'id'),p])).rows[0];}).catch(()=>null);return assignment?response.status(201).json({assignment}):response.status(409).json({code:'PROGRAM_NOT_PUBLISHED',message:'Publish the program before assignment'});});

  router.get('/client/program',auth,role('CLIENT'),async(request,response)=>{const result=await pool.query(`SELECT id,program_id "programId",snapshot,assigned_at "assignedAt" FROM program_assignments WHERE client_id=$1 AND active=true ORDER BY assigned_at DESC LIMIT 1`,[request.auth!.userId]);response.json({assignment:result.rows[0]??null});});
  router.post('/client/workouts/start',auth,role('CLIENT'),async(request,response)=>{const parsed=z.object({assignmentId:uuid,dayPosition:z.number().int().nonnegative()}).safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);const assignment=await pool.query<{coach_id:string;snapshot:{days:Array<unknown>}}>('SELECT coach_id,snapshot FROM program_assignments WHERE id=$1 AND client_id=$2 AND active=true',[parsed.data.assignmentId,request.auth!.userId]);const row=assignment.rows[0];const day=row?.snapshot.days[parsed.data.dayPosition];if(!row||!day)return response.status(404).json({code:'NOT_FOUND',message:'Assigned workout not found'});const result=await pool.query(`INSERT INTO workout_sessions(assignment_id,coach_id,client_id,day_position,workout_snapshot) VALUES($1,$2,$3,$4,$5) RETURNING *`,[parsed.data.assignmentId,row.coach_id,request.auth!.userId,parsed.data.dayPosition,day]);return response.status(201).json({session:result.rows[0]});});
  router.get('/client/workouts',auth,role('CLIENT'),async(request,response)=>response.json({sessions:(await pool.query(`SELECT id,assignment_id "assignmentId",day_position "dayPosition",workout_snapshot "workoutSnapshot",status,set_logs "setLogs",notes,started_at "startedAt",completed_at "completedAt" FROM workout_sessions WHERE client_id=$1 ORDER BY started_at DESC LIMIT 100`,[request.auth!.userId])).rows}));
  router.put('/client/workouts/:id',auth,role('CLIENT'),async(request,response)=>{const parsed=z.object({setLogs:z.array(z.object({exercisePosition:z.number().int().nonnegative(),setNumber:z.number().int().positive(),repetitions:optionalNumber,load:optionalNumber,durationSeconds:optionalNumber,rpe:z.number().min(0).max(10).nullable().optional(),notes:z.string().max(1000).optional(),completed:z.boolean()})).max(500),notes:z.string().max(4000).optional()}).safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);const result=await pool.query(`UPDATE workout_sessions SET set_logs=$1,notes=$2,updated_at=now() WHERE id=$3 AND client_id=$4 AND status='IN_PROGRESS' RETURNING id,status,set_logs "setLogs"`,[JSON.stringify(parsed.data.setLogs),parsed.data.notes??'',param(request,'id'),request.auth!.userId]);return result.rows[0]?response.json({session:result.rows[0]}):response.status(404).json({code:'NOT_FOUND',message:'Active workout not found'});});
  router.post('/client/workouts/:id/:action',auth,role('CLIENT'),async(request,response)=>{const action=param(request,'action');if(!['complete','abandon'].includes(action))return response.status(404).send();const status=action==='complete'?'COMPLETED':'ABANDONED';const result=await pool.query(`UPDATE workout_sessions SET status=$1::workout_session_status,completed_at=now(),updated_at=now() WHERE id=$2 AND client_id=$3 AND status='IN_PROGRESS' RETURNING id,status,completed_at "completedAt"`,[status,param(request,'id'),request.auth!.userId]);return result.rows[0]?response.json({session:result.rows[0]}):response.status(404).json({code:'NOT_FOUND',message:'Active workout not found'});});
  router.get('/coach/workouts',auth,role('COACH'),async(request,response)=>response.json({sessions:(await pool.query(`SELECT ws.id,ws.client_id "clientId",cp.display_name "clientName",ws.workout_snapshot "workoutSnapshot",ws.status,ws.set_logs "setLogs",ws.started_at "startedAt",ws.completed_at "completedAt" FROM workout_sessions ws JOIN client_profiles cp ON cp.user_id=ws.client_id WHERE ws.coach_id=$1 ORDER BY ws.started_at DESC LIMIT 100`,[request.auth!.userId])).rows}));

  router.put('/coach/nutrition',auth,role('COACH'),async(request,response)=>{const parsed=nutrition.safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);if(!await owns(pool,request.auth!.userId,parsed.data.clientId))return response.status(404).json({code:'NOT_FOUND',message:'Client not found'});const d=parsed.data;const result=await tx(pool,async c=>{await c.query('UPDATE nutrition_plans SET active=false,updated_at=now() WHERE coach_id=$1 AND client_id=$2 AND active=true',[request.auth!.userId,d.clientId]);return(await c.query(`INSERT INTO nutrition_plans(coach_id,client_id,daily_calories,protein_grams,carbohydrate_grams,fat_grams,meal_guidance,notes,starts_on,ends_on) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[request.auth!.userId,d.clientId,d.dailyCalories,d.proteinGrams,d.carbohydrateGrams,d.fatGrams,d.mealGuidance,d.notes,d.startsOn,d.endsOn??null])).rows[0];});return response.json({plan:result});});
  router.get('/client/nutrition',auth,role('CLIENT'),async(request,response)=>response.json({plan:(await pool.query('SELECT * FROM nutrition_plans WHERE client_id=$1 AND active=true ORDER BY created_at DESC LIMIT 1',[request.auth!.userId])).rows[0]??null,logs:(await pool.query('SELECT * FROM nutrition_logs WHERE client_id=$1 ORDER BY log_date DESC LIMIT 90',[request.auth!.userId])).rows}));
  router.put('/client/nutrition/log',auth,role('CLIENT'),async(request,response)=>{const parsed=nutritionLog.safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);const d=parsed.data;const result=await pool.query(`INSERT INTO nutrition_logs(client_id,log_date,calories,protein_grams,carbohydrate_grams,fat_grams,notes) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(client_id,log_date) DO UPDATE SET calories=excluded.calories,protein_grams=excluded.protein_grams,carbohydrate_grams=excluded.carbohydrate_grams,fat_grams=excluded.fat_grams,notes=excluded.notes RETURNING *`,[request.auth!.userId,d.logDate,d.calories,d.proteinGrams,d.carbohydrateGrams,d.fatGrams,d.notes]);return response.json({log:result.rows[0]});});
  router.get('/client/progress',auth,role('CLIENT'),async(request,response)=>response.json({entries:(await pool.query('SELECT * FROM progress_entries WHERE client_id=$1 ORDER BY measurement_date DESC LIMIT 365',[request.auth!.userId])).rows}));
  router.put('/client/progress',auth,role('CLIENT'),async(request,response)=>{const parsed=progress.safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);const d=parsed.data;const result=await pool.query(`INSERT INTO progress_entries(client_id,measurement_date,body_weight,waist,chest,arm,notes) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(client_id,measurement_date) DO UPDATE SET body_weight=excluded.body_weight,waist=excluded.waist,chest=excluded.chest,arm=excluded.arm,notes=excluded.notes RETURNING *`,[request.auth!.userId,d.measurementDate,d.bodyWeight??null,d.waist??null,d.chest??null,d.arm??null,d.notes]);return response.json({entry:result.rows[0]});});
  router.get('/coach/clients/:clientId/progress',auth,role('COACH'),async(request,response)=>{const clientId=param(request,'clientId');if(!await owns(pool,request.auth!.userId,clientId))return response.status(404).json({code:'NOT_FOUND',message:'Client not found'});return response.json({entries:(await pool.query('SELECT * FROM progress_entries WHERE client_id=$1 ORDER BY measurement_date DESC LIMIT 365',[clientId])).rows});});


  router.get('/feedback',auth,async(request,response)=>{const context=typeof request.query.context==='string'?request.query.context:'GENERAL';const contextId=typeof request.query.contextId==='string'?request.query.contextId:null;const clientId=request.auth!.role==='CLIENT'?request.auth!.userId:typeof request.query.clientId==='string'?request.query.clientId:'';const tenant=await resolvePair(pool,request.auth!,clientId);if(!tenant)return response.status(404).json({code:'NOT_FOUND',message:'Thread not found'});const result=await pool.query(`SELECT fm.id,fm.author_user_id "authorUserId",u.email author,fm.message,fm.created_at "createdAt" FROM feedback_messages fm JOIN users u ON u.id=fm.author_user_id WHERE fm.coach_id=$1 AND fm.client_id=$2 AND fm.context=$3::feedback_context AND fm.context_id IS NOT DISTINCT FROM $4 ORDER BY fm.created_at`,[tenant.coachId,tenant.clientId,context,contextId]);return response.json({messages:result.rows});});
  router.post('/feedback',auth,async(request,response)=>{const parsed=z.object({clientId:uuid.optional(),context:z.enum(['GENERAL','WORKOUT','CHECKIN']),contextId:uuid.nullable().optional(),message:z.string().trim().min(1).max(4000)}).safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);const clientId=request.auth!.role==='CLIENT'?request.auth!.userId:parsed.data.clientId??'';const tenant=await resolvePair(pool,request.auth!,clientId);if(!tenant)return response.status(404).json({code:'NOT_FOUND',message:'Thread not found'});const result=await pool.query(`INSERT INTO feedback_messages(coach_id,client_id,author_user_id,context,context_id,message) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,author_user_id "authorUserId",message,created_at "createdAt"`,[tenant.coachId,tenant.clientId,request.auth!.userId,parsed.data.context,parsed.data.contextId??null,parsed.data.message]);return response.status(201).json({message:result.rows[0]});});
  router.put('/coach/subscription',auth,role('COACH'),async(request,response)=>{const parsed=subscription.safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);if(!await owns(pool,request.auth!.userId,parsed.data.clientId))return response.status(404).json({code:'NOT_FOUND',message:'Client not found'});const d=parsed.data;const result=await pool.query(`INSERT INTO subscriptions(coach_id,client_id,plan_name,status,starts_on,ends_or_renews_on,amount,currency,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(coach_id,client_id) DO UPDATE SET plan_name=excluded.plan_name,status=excluded.status,starts_on=excluded.starts_on,ends_or_renews_on=excluded.ends_or_renews_on,amount=excluded.amount,currency=excluded.currency,notes=excluded.notes,updated_at=now() RETURNING *`,[request.auth!.userId,d.clientId,d.planName,d.status,d.startsOn,d.endsOrRenewsOn??null,d.amount??null,d.currency?.toUpperCase()??null,d.notes]);return response.json({subscription:result.rows[0]});});
  router.get('/client/subscription',auth,role('CLIENT'),async(request,response)=>response.json({subscription:(await pool.query('SELECT * FROM subscriptions WHERE client_id=$1',[request.auth!.userId])).rows[0]??null}));
  router.get('/coach/mvp-overview',auth,role('COACH'),async(request,response)=>{const id=request.auth!.userId;const result=await pool.query<{active_clients:string;programs:string;pending_checkins:string;completed_workouts:string}>(`SELECT (SELECT count(*) FROM coach_clients WHERE coach_id=$1 AND status='APPROVED') active_clients,(SELECT count(*) FROM programs WHERE coach_id=$1 AND status!='ARCHIVED') programs,(SELECT count(*) FROM checkin_submissions WHERE coach_id=$1 AND status='SUBMITTED') pending_checkins,(SELECT count(*) FROM workout_sessions WHERE coach_id=$1 AND status='COMPLETED') completed_workouts`,[id]);response.json({overview:result.rows[0]});});
  return router;
}

async function saveTemplate(pool:Pool,request:AuthenticatedRequest,response:Response,id?:string){const parsed=template.safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);try{const result=await tx(pool,async c=>{let templateId=id;if(id){const updated=await c.query('UPDATE workout_templates SET name=$1,description=$2,updated_at=now() WHERE id=$3 AND coach_id=$4 AND archived_at IS NULL RETURNING id',[parsed.data.name,parsed.data.description,id,request.auth!.userId]);if(!updated.rows[0])throw new Error('NOT_FOUND');await c.query('DELETE FROM workout_template_exercises WHERE template_id=$1',[id]);}else templateId=(await c.query<{id:string}>('INSERT INTO workout_templates(coach_id,name,description) VALUES($1,$2,$3) RETURNING id',[request.auth!.userId,parsed.data.name,parsed.data.description])).rows[0]!.id;for(const [position,item] of parsed.data.exercises.entries())await c.query(`INSERT INTO workout_template_exercises(template_id,exercise_external_id,position,sets,repetitions,duration_seconds,rest_seconds,target_rpe,tempo,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[templateId,item.exerciseId,position,item.sets,item.repetitions??null,item.durationSeconds??null,item.restSeconds,item.targetRpe??null,item.tempo??null,item.notes??null]);return{id:templateId};});return response.status(id?200:201).json({template:result});}catch{return response.status(409).json({code:'INVALID_TEMPLATE',message:'Check exercise IDs and ownership'});}}
async function saveProgram(pool:Pool,request:AuthenticatedRequest,response:Response,id?:string){const parsed=program.safeParse(request.body);if(!parsed.success)return invalid(response,parsed.error);try{const result=await tx(pool,async c=>{let programId=id;if(id){const updated=await c.query(`UPDATE programs SET name=$1,description=$2,updated_at=now() WHERE id=$3 AND coach_id=$4 AND status='DRAFT' RETURNING id`,[parsed.data.name,parsed.data.description,id,request.auth!.userId]);if(!updated.rows[0])throw new Error('NOT_FOUND');await c.query('DELETE FROM program_days WHERE program_id=$1',[id]);}else programId=(await c.query<{id:string}>('INSERT INTO programs(coach_id,name,description) VALUES($1,$2,$3) RETURNING id',[request.auth!.userId,parsed.data.name,parsed.data.description])).rows[0]!.id;for(const [position,day] of parsed.data.days.entries()){const owned=await c.query('SELECT 1 FROM workout_templates WHERE id=$1 AND coach_id=$2 AND archived_at IS NULL',[day.templateId,request.auth!.userId]);if(!owned.rows[0])throw new Error('NOT_FOUND');await c.query('INSERT INTO program_days(program_id,template_id,position,day_label) VALUES($1,$2,$3,$4)',[programId,day.templateId,position,day.dayLabel]);}return{id:programId};});return response.status(id?200:201).json({program:result});}catch{return response.status(409).json({code:'INVALID_PROGRAM',message:'Check workout ownership and program status'});}}
async function programSnapshot(c:PoolClient,id:string,coachId:string){const p=await c.query<{id:string;name:string;description:string}>(`SELECT id,name,description FROM programs WHERE id=$1 AND coach_id=$2 AND status='PUBLISHED' FOR UPDATE`,[id,coachId]);if(!p.rows[0])return null;const days=await c.query(`SELECT pd.position,pd.day_label "dayLabel",wt.id "templateId",wt.name,wt.description,COALESCE(json_agg(json_build_object('exerciseId',e.external_id,'name',e.name,'instructions',e.instructions,'gifAvailable',e.gif_available,'position',wte.position,'sets',wte.sets,'repetitions',wte.repetitions,'durationSeconds',wte.duration_seconds,'restSeconds',wte.rest_seconds,'targetRpe',wte.target_rpe,'tempo',wte.tempo,'notes',wte.notes) ORDER BY wte.position) FILTER(WHERE wte.id IS NOT NULL),'[]') exercises FROM program_days pd JOIN workout_templates wt ON wt.id=pd.template_id LEFT JOIN workout_template_exercises wte ON wte.template_id=wt.id LEFT JOIN exercises e ON e.external_id=wte.exercise_external_id WHERE pd.program_id=$1 GROUP BY pd.id,wt.id ORDER BY pd.position`,[id]);return{...p.rows[0],days:days.rows,snapshotAt:new Date().toISOString()};}
async function owns(pool:Pool,coachId:string,clientId:string){return Boolean((await pool.query(`SELECT 1 FROM coach_clients cc JOIN users u ON u.id=cc.client_id WHERE cc.coach_id=$1 AND cc.client_id=$2 AND cc.status='APPROVED' AND u.account_status='APPROVED'`,[coachId,clientId])).rows[0]);}
async function clientTenant(pool:Pool,clientId:string){const r=await pool.query<{coach_id:string}>(`SELECT coach_id FROM coach_clients WHERE client_id=$1 AND status='APPROVED'`,[clientId]);return r.rows[0]?{coachId:r.rows[0].coach_id,clientId}:null;}
async function resolvePair(pool:Pool,auth:NonNullable<AuthenticatedRequest['auth']>,clientId:string){if(auth.role==='CLIENT')return clientTenant(pool,auth.userId);if(auth.role==='COACH'&&await owns(pool,auth.userId,clientId))return{coachId:auth.userId,clientId};return null;}
async function tx<T>(pool:Pool,work:(client:PoolClient)=>Promise<T>){const client=await pool.connect();try{await client.query('BEGIN');const value=await work(client);await client.query('COMMIT');return value;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
function param(request:AuthenticatedRequest,name:string){const value=request.params[name];return typeof value==='string'?value:'';}function invalid(response:Response,error:z.ZodError){return response.status(400).json({code:'VALIDATION_ERROR',message:'Check the submitted fields',details:error.flatten().fieldErrors});}
